"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ChevronRight, Pause, Play, RotateCcw, Shuffle, Sparkles, X } from "lucide-react";
import "./cat-bomb.css";
import "./cat-bomb-timer.css";
import "./cat-bomb-polish.css";
import "./cat-bomb-rules.css";

const bombOverlayStyle:React.CSSProperties={position:"fixed",inset:0,zIndex:120};

type Mode="cat"|"player";
type Stage="setup"|"host"|"ready"|"play"|"boom";
type Item={name:string;icon:string;rarity:string;instant?:boolean;description:string;scope?:"common"|"catbomb"};
const item=(name:string,icon:string,rarity:string,description:string,instant=false,scope:"common"|"catbomb"="catbomb"):Item=>({name,icon,rarity,description,instant,scope});
const ranges:Record<number,number>={2:50,3:80,4:100,5:130,6:160,7:190,8:210,9:250,10:250};
const boxItems:Item[]=[
  item("数字提示","📈","普通","随机获得一条不可重复查看的基础线索：奇偶或相对当前范围中点。"),item("跳过本轮","⏭️","普通","确认后立即结束当前回合，把炸弹交给下一位玩家。"),item("调换顺序","🔀","普通","指定一名玩家，与你交换之后所有回合的行动顺序。"),item("再抽一次","🎁","普通","立即免费再抽一个盲盒；再次抽到可继续连抽。"),
  item("猫咪恶作剧","😼","普通","猫咪藏起背包，本回合不能主动使用任何道具。",true),item("手滑","🤯","普通","确认后系统会在当前合法范围内随机替你输入一个数字。",true),item("热感仪","🔥","稀有","立刻使用后，输入数字会提示距离炸弹≤8为热，否则为冷。"),item("区域扫描","🧭","稀有","扫描炸弹所在区域，并直接缩小当前搜索范围。"),item("延长思考","⏳","稀有","本回合倒计时立即增加10秒。"),item("双重压力","😵","稀有","本回合必须连续输入两次；第一次更新范围后立刻再猜。",true),item("发呆","💤","稀有","确认后当前回合立即结束。",true),
  item("炸弹重置","🎲","史诗","在当前范围内秘密重新生成炸弹数字，玩家不会看到新答案。"),item("猫咪偷看","🔍","史诗","随机查看炸弹的十位数字或个位数字。"),item("防爆头盔","🛡️","史诗","被动触发：猜中炸弹时免于失败，重置炸弹后继续游戏。"),item("超级扫描仪","📡","传说","显示炸弹所在的约20%区间。"),item("定时炸弹","💣","传说","下一次轮到你时必须立即输入，不能跳过或使用拖延道具。",true),item("命运逆转","🌈","神话","本回合猜中炸弹时，可指定另一名玩家代替失败。"),item("猫咪诅咒","😈","神话","接下来连续两次轮到你时不能抽盲盒。",true)
];
const pickBox=()=>{const r=Math.random()*100;const rarity=r<48?"普通":r<75?"稀有":r<90?"史诗":r<98?"传说":"神话";const pool=boxItems.filter(x=>x.rarity===rarity);return pool[Math.floor(Math.random()*pool.length)]};
const shuffled=<T,>(items:T[])=>[...items].sort(()=>Math.random()-.5);

export default function CatBomb({initialPlayers,onClose,onTruthOrDare}:{initialPlayers:string[];onClose:()=>void;onTruthOrDare:(loser:string)=>void}){
  const seed=initialPlayers.length>=2?initialPlayers.slice(0,10):["小明","小红"];
  const[stage,setStage]=useState<Stage>("setup"),[mode,setMode]=useState<Mode>("cat"),[names,setNames]=useState(seed),[host,setHost]=useState(seed[0]);
  const[order,setOrder]=useState(seed),[turn,setTurn]=useState(0),[low,setLow]=useState(1),[high,setHigh]=useState(ranges[seed.length]||100),[secret,setSecret]=useState(0),[hostSecret,setHostSecret]=useState("");
  const[guess,setGuess]=useState(""),[message,setMessage]=useState("炸弹很安静……暂时的。"),[loser,setLoser]=useState(""),[draws,setDraws]=useState<Record<string,number>>({}),[bags,setBags]=useState<Record<string,Item[]>>({}),[box,setBox]=useState<Item|null>(null),[event,setEvent]=useState("");
  const[timeLeft,setTimeLeft]=useState(30),[paused,setPaused]=useState(false),[drawnThisTurn,setDrawnThisTurn]=useState(false),[itemBlocked,setItemBlocked]=useState(false),[feedback,setFeedback]=useState<"high"|"low"|null>(null),[bagOpen,setBagOpen]=useState(false);
  const[confirmExit,setConfirmExit]=useState(false),[newName,setNewName]=useState(""),[doubleLeft,setDoubleLeft]=useState(0),[hotMode,setHotMode]=useState(false),[freeDraw,setFreeDraw]=useState(false),[swapItem,setSwapItem]=useState<Item|null>(null),[destinyOwner,setDestinyOwner]=useState(""),[curses,setCurses]=useState<Record<string,number>>({}),[timed,setTimed]=useState<Record<string,boolean>>({}),[eventModal,setEventModal]=useState<{icon:string;title:string;text:string}|null>(null);
  const max=useMemo(()=>ranges[names.length]||250,[names.length]);
  const active=order[turn%order.length]||names[0];
  const cursed=(curses[active]||0)>0;
  const setCount=(n:number)=>{const next=[...names];while(next.length<n)next.push(`玩家${next.length+1}`);setNames(next.slice(0,n));setHigh(ranges[n]||250)};
  const begin=()=>{const playing=mode==="player"?names.filter(n=>n!==host):names;const next=shuffled(playing);setOrder(next);setTurn(0);setLow(1);setHigh(max);setSecret(mode==="cat"?Math.floor(Math.random()*max)+1:Number(hostSecret));setStage("ready")};
  const nextTurn=(note:string)=>{setMessage(note);const roundEnd=(turn+1)%order.length===0;if(roundEnd&&Math.random()<.08){const n=Math.floor(Math.random()*4);if(n===0){setSecret(Math.floor(Math.random()*(high-low+1))+low);setEventModal({icon:"🐭",title:"老鼠捣乱",text:"老鼠碰到了炸弹。炸弹已在当前范围内重新隐藏。"})}else if(n===1){if(high-low<6)setEventModal({icon:"🌪️",title:"数字漂移失败",text:"当前范围太小，炸弹稳稳待在原地。"});else{setSecret(s=>Math.min(high,Math.max(low,s+(Math.random()<.5?-2:2))));setEventModal({icon:"🌪️",title:"数字漂移",text:"炸弹数字轻微漂移了 ±2，仍在当前范围内。"})}}else if(n===2){if(high-low<10)setEventModal({icon:"🐾",title:"猫咪踩按钮失败",text:"当前范围已经很小，机器拒绝继续压缩。"});else{const pad=Math.max(1,Math.floor((high-low)*.2));setLow(l=>Math.min(secret,l+pad));setHigh(h=>Math.max(secret,h-pad));setEventModal({icon:"🐾",title:"猫咪踩按钮",text:"机器被误触，当前数字范围自动缩小。"})}}else{setOrder(o=>shuffled(o));setEventModal({icon:"🔄",title:"顺序洗牌",text:"所有玩家的后续行动顺序已经重新随机。"})}}setEvent("");setCurses(c=>({...c,[active]:Math.max(0,(c[active]||0)-1)}));setTurn(t=>(t+1)%order.length);setBox(null);setGuess("");setTimeLeft(timed[order[(turn+1)%order.length]]?10:30);setPaused(false);setDrawnThisTurn(false);setItemBlocked(false);setDoubleLeft(0);setHotMode(false)};
  useEffect(()=>{if(stage!=="play"||paused||timeLeft<=0)return;const timer=window.setInterval(()=>setTimeLeft(t=>Math.max(0,t-1)),1000);return()=>window.clearInterval(timer)},[stage,paused,timeLeft]);
  useEffect(()=>{if(stage==="play"&&timeLeft===0)nextTurn("⏰ 30 秒到，本轮自动跳过")},[timeLeft,stage]);
  const submit=(forced?:number)=>{const n=forced??Number(guess);if(!Number.isInteger(n)||n<low||n>high){setMessage(`请输入 ${low}–${high} 之间的整数喵`);return}if(n===secret){const helmet=(bags[active]||[]).find(x=>x.name==="防爆头盔");if(helmet){setBags(b=>({...b,[active]:b[active].filter(x=>x!==helmet)}));setSecret(Math.floor(Math.random()*(high-low+1))+low);nextTurn("🛡️ 防爆头盔碎裂！炸弹已重置，游戏继续");return}const destiny=(bags[active]||[]).find(x=>x.name==="命运逆转");if(destiny){setDestinyOwner(active);setPaused(true);return}setLoser(active);setStage("boom");return}const heat=hotMode?(Math.abs(n-secret)<=8?"🔥 越来越热了！":"🥶 还差得远。"):"";if(n<secret){setLow(n+1);setFeedback("low");if(doubleLeft>1){setDoubleLeft(1);setGuess("");setMessage(`${heat||"猜低了"} · 双重压力：请立即再猜一次`)}else nextTurn(heat||"猜低了：再大胆一点喵～")}else{setHigh(n-1);setFeedback("high");if(doubleLeft>1){setDoubleLeft(1);setGuess("");setMessage(`${heat||"猜高了"} · 双重压力：请立即再猜一次`)}else nextTurn(heat||"猜高了：有点太高啦！")}};
  const draw=(free=false)=>{if(!free&&(drawnThisTurn||(draws[active]||0)>=2||cursed))return;const rolled=pickBox();if(!free){setDrawnThisTurn(true);setDraws(d=>({...d,[active]:(d[active]||0)+1}))}setBox(rolled);setFreeDraw(false)};
  const acceptNegative=()=>{if(!box)return;const x=box;setBox(null);if(x.name==="发呆"){nextTurn("💤 猫咪发呆，本轮自动跳过");return}if(x.name==="手滑"){const n=Math.floor(Math.random()*(high-low+1))+low;setGuess(String(n));setMessage(`🤯 系统替你输入了 ${n}`);window.setTimeout(()=>submit(n),350);return}if(x.name==="猫咪恶作剧"){setItemBlocked(true);setMessage("😼 背包被藏起来，本回合不能主动使用道具");return}if(x.name==="双重压力"){setDoubleLeft(2);setMessage("😵 双重压力生效：本回合必须连续猜两次");return}if(x.name==="定时炸弹"){setTimed(t=>({...t,[active]:true}));setMessage("💣 定时炸弹已绑定：下次轮到你时只有10秒且不能拖延");return}if(x.name==="猫咪诅咒"){setCurses(c=>({...c,[active]:2}));setMessage("😈 猫咪诅咒：接下来两次轮到你都不能抽盲盒")}};
  const storeItem=()=>{if(!box)return;setBags(b=>{const bag=b[active]||[];return {...b,[active]:[...bag.slice(-2),box]}});setMessage(`${box.icon} ${box.name} 已放入背包`);setBox(null)};
  const useItem=(item:Item,fromBag=false)=>{if(fromBag)setBags(b=>({...b,[active]:(b[active]||[]).filter(x=>x!==item)}));setBox(null);setBagOpen(false);if(item.name==="跳过本轮"){nextTurn("⏭️ 已确认跳过，本轮安全交棒");return}if(item.name==="调换顺序"){setSwapItem(item);return}if(item.name==="再抽一次"){setFreeDraw(true);window.setTimeout(()=>draw(true),0);return}if(item.name==="炸弹重置"){setSecret(Math.floor(Math.random()*(high-low+1))+low);setMessage("🎲 炸弹已在当前范围内秘密重置");return}if(item.name==="数字提示"){const mid=Math.floor((low+high)/2),hints=[`炸弹数字是${secret%2?"奇数":"偶数"}`,`炸弹数字${secret>mid?"大于":"小于或等于"}当前范围中点 ${mid}`];setMessage(`📈 ${hints[Math.floor(Math.random()*hints.length)]}`);return}if(item.name==="区域扫描"||item.name==="超级扫描仪"){const size=item.name==="超级扫描仪"?Math.max(3,Math.ceil((high-low+1)*.2)):Math.max(8,Math.ceil((high-low+1)*.35));let a=Math.max(low,secret-Math.floor(Math.random()*size)),b=Math.min(high,a+size-1);a=Math.max(low,b-size+1);setLow(a);setHigh(b);setMessage(`📡 扫描结果：炸弹一定在 ${a}–${b} 之间`);return}if(item.name==="延长思考"){setTimeLeft(t=>t+10);setMessage("⏳ 本回合思考时间增加10秒");return}if(item.name==="猫咪偷看"){const tens=Math.floor(secret/10);setMessage(Math.random()<.5?`🔍 十位数字是 ${tens}`:`🔍 个位数字是 ${secret%10}`);return}if(item.name==="热感仪"){setHotMode(true);setMessage("🔥 热感仪已启动：请输入一个数字检测冷热");return}if(item.name==="防爆头盔"){setBags(b=>({...b,[active]:[...(b[active]||[]),item].slice(-3)}));setMessage("🛡️ 防爆头盔已佩戴，将在猜中炸弹时自动触发");return}setMessage(`${item.icon} ${item.name} 已立即使用`)};
  const reset=()=>{setStage("setup");setDraws({});setBags({});setBox(null);setLoser("");setEvent("")};
  return <div className="play-screen bomb-screen" style={bombOverlayStyle}><header className="play-head"><button onClick={()=>setConfirmExit(true)}><ArrowLeft/></button><b>猫咪炸弹</b><span>🐾</span></header><div className="bomb-shell">
    {stage==="setup"&&<><div className="bomb-hero"><img src={`${process.env.NEXT_PUBLIC_BASE_PATH||""}/icons/games/cat-bomb.png`} alt="抱着炸弹的小白猫"/><div><small>CAT BOMB · 猫猫主持</small><h1>数字越猜越近，<br/>心跳越来越快。</h1><p>猜中不是胜利——是 💥 BOOM！</p></div></div><section className="bomb-panel"><h2>选择模式</h2><div className="bomb-modes"><button className={mode==="cat"?"on":""} onClick={()=>setMode("cat")}><span>🐱</span><b>小猫主持人</b><small>答案保密，系统主持全局</small></button><button className={mode==="player"?"on":""} onClick={()=>setMode("player")}><span>👤</span><b>玩家主持人</b><small>由一位玩家偷偷设下炸弹</small></button></div><div className="bomb-count"><b>本局人数</b><div><button onClick={()=>setCount(Math.max(2,names.length-1))}>−</button><strong>{names.length}</strong><button onClick={()=>setCount(Math.min(10,names.length+1))}>＋</button></div></div><div className="bomb-range"><span>推荐数字范围</span><b>1 — {max}</b><small>人数越多，范围自动越大</small></div><button className="primary full" onClick={()=>setStage(mode==="player"?"host":"host")}>下一步 <ChevronRight/></button></section></>}
    {stage==="host"&&<section className="bomb-panel bomb-setup"><span className="bomb-kicker">{mode==="cat"?"🐱 小猫正在点名":"👤 选一位主持人"}</span><h1>{mode==="cat"?"确认玩家名单":"谁来藏起炸弹？"}</h1><div className="bomb-name-grid">{names.map((n,i)=><label key={i} className={mode==="player"&&host===n?"on":""}><input value={n} onChange={e=>setNames(a=>a.map((x,j)=>j===i?e.target.value:x))} onClick={()=>mode==="player"&&setHost(n)}/>{mode==="player"&&<button onClick={()=>setHost(n)}>{host===n?"主持人":"选择"}</button>}</label>)}</div><div className="add-bomb-player"><input value={newName} onChange={e=>setNewName(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&newName.trim()&&names.length<10){setNames(n=>[...n,newName.trim()]);setNewName("")}}} placeholder="输入名字加入玩家"/><button disabled={!newName.trim()||names.length>=10} onClick={()=>{setNames(n=>[...n,newName.trim()]);setNewName("")}}>＋ 加入</button></div>{mode==="player"&&<><button className="secondary full" onClick={()=>setHost(names[Math.floor(Math.random()*names.length)])}><Shuffle/> 随机主持人</button><label className="secret-input"><span>{host} 输入秘密数字</span><input type="password" inputMode="numeric" value={hostSecret} onChange={e=>setHostSecret(e.target.value)} placeholder={`1–${max}`}/><small>输入后点击开始，再把手机交给第一位玩家</small></label></>}<button className="primary full" disabled={mode==="player"&&(+hostSecret<1||+hostSecret>max)} onClick={begin}>生成随机顺序 <Sparkles/></button></section>}
    {stage==="ready"&&<section className="bomb-panel bomb-center ready-card"><span className="big-emoji">🔀</span><small>本局出场顺序</small><h1>{order.join(" → ")}</h1><div className="bomb-range ready-range"><div><span>炸弹藏在数字范围</span><small>{mode==="cat"?"答案由猫咪保密":"主持人请保持神秘"}</small></div><b>1 — {max}</b></div><button className="primary full" onClick={()=>setStage("play")}>把手机交给 {order[0]} <ChevronRight/></button></section>}
    {stage==="play"&&<><div className="bomb-status"><div><small>安全范围</small><b>{low} — {high}</b><span>{high-low<15?"😨 炸弹开始冒烟了！":"引线正在滋滋作响…"}</span></div><img src={`${process.env.NEXT_PUBLIC_BASE_PATH||""}/icons/games/cat-bomb.png`} alt="猫咪炸弹"/></div><section className="bomb-panel turn-panel"><div className="player-order-strip">{order.map((name,i)=><span className={name===active?"active":""} key={`${name}${i}`}>{name}</span>)}</div><div className="turn-head"><span>{turn+1}</span><div><small>现在轮到</small><h1>{active}</h1></div><em>{doubleLeft?`还需猜 ${doubleLeft} 次`:`整局盲盒 ${draws[active]||0}/2`}</em></div><div className={`turn-timer ${timeLeft<=10?"urgent":""} ${paused?"paused":""}`}><div><small>本回合剩余</small><b>{String(timeLeft).padStart(2,"0")}s</b><span>{timed[active]?"定时炸弹：立即输入":"包含开盲盒时间"}</span></div><button onClick={()=>setPaused(p=>!p)}>{paused?<Play/>:<Pause/>}{paused?"继续":"暂停"}</button></div>{event&&<div className="bomb-event">{event}</div>}<div className="bomb-message">{feedback&&<img src={`${process.env.NEXT_PUBLIC_BASE_PATH||""}/icons/cat-bomb/${feedback==="high"?"too-high-v2":"too-low-v2"}.png`} alt={feedback==="high"?"猜高了":"猜低了"}/>}<p>{message}</p></div><div className="bomb-actions"><button disabled={drawnThisTurn||(draws[active]||0)>=2||cursed||timed[active]} onClick={()=>draw()}><img src={`${process.env.NEXT_PUBLIC_BASE_PATH||""}/icons/cat-bomb/blindbox-v2.png`} alt="抽盲盒小猫"/><span><b>{cursed?"猫咪诅咒中":drawnThisTurn?"本轮已开启":"抽盲盒"}</b><small>{cursed?`还剩 ${curses[active]} 轮`:"每轮最多 1 次"}</small></span></button><button disabled={itemBlocked||!(bags[active]||[]).length||timed[active]} onClick={()=>setBagOpen(true)}><img src={`${process.env.NEXT_PUBLIC_BASE_PATH||""}/icons/cat-bomb/backpack-v2.png`} alt="背道具包的小猫"/><span><b>{itemBlocked?"本轮被禁用":"使用背包"}</b><small>{(bags[active]||[]).length}/3 个专属道具</small></span></button></div><label className="guess-input"><span>输入你的数字</span><div><input disabled={box?.instant&&box.name==="手滑"} inputMode="numeric" value={guess} onChange={e=>setGuess(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder={`${low} — ${high}`}/><button onClick={()=>submit()}>确认</button></div></label></section>{bagOpen&&<div className="bag-overlay"><div className="bag-sheet"><button className="bag-close" onClick={()=>setBagOpen(false)}><X/></button><img src={`${process.env.NEXT_PUBLIC_BASE_PATH||""}/icons/cat-bomb/backpack-v2.png`} alt="道具背包"/><h2>{active} 的猫咪炸弹背包</h2><p>专属道具最多3个，不占用通用道具栏</p><div>{(bags[active]||[]).map((item,i)=><button key={`${item.name}${i}`} onClick={()=>useItem(item,true)}><span>{item.icon}</span><b>{item.name}</b><small>{item.rarity}</small></button>)}</div></div></div>}</>}
    {stage==="boom"&&<section className="bomb-panel bomb-center boom-card"><img className="boom-main" src={`${process.env.NEXT_PUBLIC_BASE_PATH||""}/icons/cat-bomb/boom-v2.png`} alt="BOOM 爆炸猫咪"/><small>炸弹数字是 {secret}</small><h1>{loser} 被炸成小黑炭啦！</h1><img className="charred-cat" src={`${process.env.NEXT_PUBLIC_BASE_PATH||""}/icons/cat-bomb/charred-v2.png`} alt="被炸黑的猫咪"/><p>失败者可以选择真心话、大冒险，也可以安心跳过。</p><button className="primary full" onClick={()=>onTruthOrDare(loser)}>🎭 真心话 / 🎯 大冒险</button><button className="secondary full" onClick={onClose}>😊 跳过惩罚</button><button className="text-btn" onClick={reset}><RotateCcw/> 再来一局</button></section>}
    {box&&<div className="effect-overlay"><div className={`effect-card ${box.instant?"negative":""}`}><img src={`${process.env.NEXT_PUBLIC_BASE_PATH||""}/icons/cat-bomb/blindbox-v2.png`} alt="小猫抱着问号盲盒"/><small>{box.rarity} · {box.instant?"负面效果":"正面道具"}</small><h2>{box.icon} {box.name}</h2><p>{box.description}</p>{box.instant?<button className="primary full" onClick={acceptNegative}>知道了，只能接受</button>:<div><button className="primary" onClick={()=>useItem(box)}>立即使用</button><button className="secondary" onClick={storeItem}>放入背包</button></div>}</div></div>}
    {swapItem&&<div className="effect-overlay"><div className="effect-card"><h2>🔀 与谁调换顺序？</h2><p>只改变之后的行动顺序，不影响已经完成的回合。</p><div className="target-grid">{order.filter(n=>n!==active).map(name=><button key={name} onClick={()=>{setOrder(o=>{const a=o.indexOf(active),b=o.indexOf(name),n=[...o];[n[a],n[b]]=[n[b],n[a]];return n});setSwapItem(null);setMessage(`🔀 已与 ${name} 调换后续顺序`)}}>{name}</button>)}</div></div></div>}
    {destinyOwner&&<div className="effect-overlay"><div className="effect-card"><h2>🌈 命运逆转</h2><p>你猜中了炸弹。指定一名玩家替你成为失败者。</p><div className="target-grid">{order.filter(n=>n!==destinyOwner).map(name=><button key={name} onClick={()=>{setBags(b=>({...b,[destinyOwner]:(b[destinyOwner]||[]).filter(x=>x.name!=="命运逆转")}));setLoser(name);setDestinyOwner("");setStage("boom")}}>{name}</button>)}</div></div></div>}
    {eventModal&&<div className="effect-overlay"><div className="effect-card event-card"><span>{eventModal.icon}</span><small>每轮结束 · 8% 随机事件</small><h2>{eventModal.title}</h2><p>{eventModal.text}</p><button className="primary full" onClick={()=>setEventModal(null)}>继续游戏</button></div></div>}
    {confirmExit&&<div className="effect-overlay"><div className="effect-card exit-card"><img src={`${process.env.NEXT_PUBLIC_BASE_PATH||""}/icons/games/catbomb-yellow.png`} alt="嫩黄色猫咪炸弹"/><h2>要离开这局吗？</h2><p>当前范围、玩家顺序和本局道具效果都会结束。</p><div><button className="secondary" onClick={()=>setConfirmExit(false)}>继续游戏</button><button className="danger" onClick={onClose}>确认退出</button></div></div></div>}
  </div></div>
}
