"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Backpack, ChevronRight, Gift, Pause, Play, RotateCcw, Shuffle, Sparkles } from "lucide-react";
import "./cat-bomb.css";
import "./cat-bomb-timer.css";

const bombOverlayStyle:React.CSSProperties={position:"fixed",inset:0,zIndex:120};

type Mode="cat"|"player";
type Stage="setup"|"host"|"ready"|"play"|"boom";
type Item={name:string;icon:string;rarity:string;instant?:boolean};
const ranges:Record<number,number>={2:50,3:80,4:100,5:130,6:160,7:190,8:210,9:250,10:250};
const boxItems:Item[]=[
  {name:"数字提示",icon:"💡",rarity:"普通"},{name:"跳过本轮",icon:"⏭️",rarity:"普通"},{name:"调换顺序",icon:"🔀",rarity:"普通"},{name:"再抽一次",icon:"🎁",rarity:"普通"},
  {name:"猫咪恶作剧",icon:"😼",rarity:"普通",instant:true},{name:"手滑",icon:"🤯",rarity:"普通",instant:true},{name:"热感仪",icon:"🌡️",rarity:"稀有"},{name:"区域扫描",icon:"🧭",rarity:"稀有"},{name:"延长思考",icon:"⏳",rarity:"稀有"},{name:"双重压力",icon:"😵",rarity:"稀有",instant:true},{name:"发呆",icon:"💤",rarity:"稀有",instant:true},
  {name:"炸弹重置",icon:"🎲",rarity:"史诗"},{name:"猫咪偷看",icon:"🔍",rarity:"史诗"},{name:"防爆头盔",icon:"🪖",rarity:"史诗"},{name:"超级扫描仪",icon:"📡",rarity:"传说"},{name:"猫皇赐福",icon:"👑",rarity:"传说"},{name:"定时炸弹",icon:"⏱️",rarity:"传说",instant:true},{name:"命运逆转",icon:"🌈",rarity:"神话"},{name:"猫咪诅咒",icon:"😈",rarity:"神话",instant:true}
];
const pickBox=()=>{const r=Math.random()*100;const rarity=r<48?"普通":r<75?"稀有":r<90?"史诗":r<98?"传说":"神话";const pool=boxItems.filter(x=>x.rarity===rarity);return pool[Math.floor(Math.random()*pool.length)]};
const shuffled=<T,>(items:T[])=>[...items].sort(()=>Math.random()-.5);

export default function CatBomb({initialPlayers,onClose,onTruthOrDare}:{initialPlayers:string[];onClose:()=>void;onTruthOrDare:(loser:string)=>void}){
  const seed=initialPlayers.length>=2?initialPlayers.slice(0,10):["小明","小红"];
  const[stage,setStage]=useState<Stage>("setup"),[mode,setMode]=useState<Mode>("cat"),[names,setNames]=useState(seed),[host,setHost]=useState(seed[0]);
  const[order,setOrder]=useState(seed),[turn,setTurn]=useState(0),[low,setLow]=useState(1),[high,setHigh]=useState(ranges[seed.length]||100),[secret,setSecret]=useState(0),[hostSecret,setHostSecret]=useState("");
  const[guess,setGuess]=useState(""),[message,setMessage]=useState("炸弹很安静……暂时的。"),[loser,setLoser]=useState(""),[draws,setDraws]=useState<Record<string,number>>({}),[bags,setBags]=useState<Record<string,Item[]>>({}),[box,setBox]=useState<Item|null>(null),[event,setEvent]=useState("");
  const[timeLeft,setTimeLeft]=useState(30),[paused,setPaused]=useState(false),[drawnThisTurn,setDrawnThisTurn]=useState(false),[itemBlocked,setItemBlocked]=useState(false),[feedback,setFeedback]=useState<"high"|"low"|null>(null);
  const max=useMemo(()=>ranges[names.length]||250,[names.length]);
  const active=order[turn%order.length]||names[0];
  const setCount=(n:number)=>{const next=[...names];while(next.length<n)next.push(`玩家${next.length+1}`);setNames(next.slice(0,n));setHigh(ranges[n]||250)};
  const begin=()=>{const playing=mode==="player"?names.filter(n=>n!==host):names;const next=shuffled(playing);setOrder(next);setTurn(0);setLow(1);setHigh(max);setSecret(mode==="cat"?Math.floor(Math.random()*max)+1:Number(hostSecret));setStage("ready")};
  const nextTurn=(note:string)=>{setMessage(note);if(Math.random()<.08){const events=["🐭 老鼠捣乱：炸弹换了位置！","🌪 数字漂移：炸弹悄悄挪动了。","🐾 猫咪踩按钮：范围突然紧张起来！","🔄 顺序洗牌：猫猫重新排了队！"];const e=events[Math.floor(Math.random()*events.length)];setEvent(e);if(e.includes("老鼠"))setSecret(Math.floor(Math.random()*(high-low+1))+low);if(e.includes("漂移"))setSecret(s=>Math.min(high,Math.max(low,s+(Math.random()<.5?-2:2))));if(e.includes("洗牌"))setOrder(o=>shuffled(o));}else setEvent("");setTurn(t=>(t+1)%order.length);setBox(null);setGuess("");setTimeLeft(30);setPaused(false);setDrawnThisTurn(false);setItemBlocked(false)};
  useEffect(()=>{if(stage!=="play"||paused||timeLeft<=0)return;const timer=window.setInterval(()=>setTimeLeft(t=>Math.max(0,t-1)),1000);return()=>window.clearInterval(timer)},[stage,paused,timeLeft]);
  useEffect(()=>{if(stage==="play"&&timeLeft===0)nextTurn("⏰ 30 秒到，本轮自动跳过")},[timeLeft,stage]);
  const submit=(forced?:number)=>{const n=forced??Number(guess);if(!Number.isInteger(n)||n<low||n>high){setMessage(`请输入 ${low}–${high} 之间的整数喵`);return}if(n===secret){const helmet=(bags[active]||[]).find(x=>x.name==="防爆头盔");if(helmet){setBags(b=>({...b,[active]:b[active].filter(x=>x!==helmet)}));setSecret(Math.floor(Math.random()*(high-low+1))+low);nextTurn("🪖 防爆头盔救了你！炸弹已重置");return}setLoser(active);setStage("boom");return}if(n<secret){setLow(n+1);setFeedback("low");nextTurn("猜低了：再大胆一点喵～")}else{setHigh(n-1);setFeedback("high");nextTurn("猜高了：有点太高啦！")}};
  const draw=()=>{if(drawnThisTurn||(draws[active]||0)>=2)return;const item=pickBox();setDrawnThisTurn(true);setDraws(d=>({...d,[active]:(d[active]||0)+1}));setBox(item);if(!item.instant)setBags(b=>{const bag=b[active]||[];return {...b,[active]:[...bag.slice(-2),item]}});else if(item.name==="发呆")nextTurn("💤 抽到发呆，本轮立即跳过");else if(item.name==="手滑"){const n=Math.floor(Math.random()*(high-low+1))+low;setGuess(String(n));setMessage(`🤯 手滑！猫咪替你输入了 ${n}`);window.setTimeout(()=>submit(n),350)}else if(item.name==="猫咪恶作剧"){setItemBlocked(true);setMessage("😼 猫咪恶作剧：本轮立即禁用背包道具")}else setMessage(`${item.icon} ${item.name}：负面效果立即生效！`)};
  const reset=()=>{setStage("setup");setDraws({});setBags({});setBox(null);setLoser("");setEvent("")};
  return <div className="play-screen bomb-screen" style={bombOverlayStyle}><header className="play-head"><button onClick={onClose}><ArrowLeft/></button><b>猫咪炸弹</b><span>🐾</span></header><div className="bomb-shell">
    {stage==="setup"&&<><div className="bomb-hero"><img src={`${process.env.NEXT_PUBLIC_BASE_PATH||""}/icons/games/cat-bomb.png`} alt="抱着炸弹的小白猫"/><div><small>CAT BOMB · 猫猫主持</small><h1>数字越猜越近，<br/>心跳越来越快。</h1><p>猜中不是胜利——是 💥 BOOM！</p></div></div><section className="bomb-panel"><h2>选择模式</h2><div className="bomb-modes"><button className={mode==="cat"?"on":""} onClick={()=>setMode("cat")}><span>🐱</span><b>小猫主持人</b><small>答案保密，系统主持全局</small></button><button className={mode==="player"?"on":""} onClick={()=>setMode("player")}><span>👤</span><b>玩家主持人</b><small>由一位玩家偷偷设下炸弹</small></button></div><div className="bomb-count"><b>本局人数</b><div><button onClick={()=>setCount(Math.max(2,names.length-1))}>−</button><strong>{names.length}</strong><button onClick={()=>setCount(Math.min(10,names.length+1))}>＋</button></div></div><div className="bomb-range"><span>推荐数字范围</span><b>1 — {max}</b><small>人数越多，范围自动越大</small></div><button className="primary full" onClick={()=>setStage(mode==="player"?"host":"host")}>下一步 <ChevronRight/></button></section></>}
    {stage==="host"&&<section className="bomb-panel bomb-setup"><span className="bomb-kicker">{mode==="cat"?"🐱 小猫正在点名":"👤 选一位主持人"}</span><h1>{mode==="cat"?"确认玩家名单":"谁来藏起炸弹？"}</h1><div className="bomb-name-grid">{names.map((n,i)=><label key={i} className={mode==="player"&&host===n?"on":""}><input value={n} onChange={e=>setNames(a=>a.map((x,j)=>j===i?e.target.value:x))} onClick={()=>mode==="player"&&setHost(n)}/>{mode==="player"&&<button onClick={()=>setHost(n)}>{host===n?"主持人":"选择"}</button>}</label>)}</div>{mode==="player"&&<><button className="secondary full" onClick={()=>setHost(names[Math.floor(Math.random()*names.length)])}><Shuffle/> 随机主持人</button><label className="secret-input"><span>{host} 输入秘密数字</span><input type="password" inputMode="numeric" value={hostSecret} onChange={e=>setHostSecret(e.target.value)} placeholder={`1–${max}`}/><small>输入后点击开始，再把手机交给第一位玩家</small></label></>}<button className="primary full" disabled={mode==="player"&&(+hostSecret<1||+hostSecret>max)} onClick={begin}>生成随机顺序 <Sparkles/></button></section>}
    {stage==="ready"&&<section className="bomb-panel bomb-center"><span className="big-emoji">🔀</span><small>本局出场顺序</small><h1>{order.join(" → ")}</h1><div className="bomb-range"><span>炸弹藏在</span><b>1 — {max}</b><small>{mode==="cat"?"没有人知道答案":"主持人请保持神秘"}</small></div><button className="primary full" onClick={()=>setStage("play")}>把手机交给 {order[0]} <ChevronRight/></button></section>}
    {stage==="play"&&<><div className="bomb-status"><div><small>安全范围</small><b>{low} — {high}</b><span>{high-low<15?"😨 炸弹开始冒烟了！":"引线正在滋滋作响…"}</span></div><img src={`${process.env.NEXT_PUBLIC_BASE_PATH||""}/icons/games/cat-bomb.png`} alt="猫咪炸弹"/></div><section className="bomb-panel"><div className="turn-head"><span>{turn+1}</span><div><small>现在轮到</small><h1>{active}</h1></div><em>整局已抽 {draws[active]||0}/2</em></div><div className={`turn-timer ${timeLeft<=10?"urgent":""} ${paused?"paused":""}`}><div><small>本回合剩余</small><b>{String(timeLeft).padStart(2,"0")}s</b><span>包含开盲盒时间</span></div><button onClick={()=>setPaused(p=>!p)}>{paused?<Play/>:<Pause/>}{paused?"继续":"暂停"}</button></div>{event&&<div className="bomb-event">{event}</div>}<div className="bomb-message">{feedback&&<img src={`${process.env.NEXT_PUBLIC_BASE_PATH||""}/icons/cat-bomb/${feedback==="high"?"too-high":"too-low"}.png`} alt={feedback==="high"?"猜高了":"猜低了"}/>}<p>{message}</p></div><div className="bomb-actions"><button disabled={drawnThisTurn||(draws[active]||0)>=2} onClick={draw}><Gift/><b>{drawnThisTurn?"本轮已开启":"抽盲盒"}</b><small>每轮最多 1 次</small></button><button disabled={itemBlocked||!(bags[active]||[]).length}><Backpack/><b>{itemBlocked?"本轮被禁用":"使用背包"}</b><small>{(bags[active]||[]).length}/3 个道具</small></button></div>{box&&<div className={`box-reveal ${box.instant?"bad":""}`}><span>{box.icon}</span><div><small>{box.rarity}盲盒</small><b>{box.name}</b><em>{box.instant?"负面效果 · 已立即生效":"已放入背包"}</em></div></div>}<label className="guess-input"><span>输入你的数字</span><div><input inputMode="numeric" value={guess} onChange={e=>setGuess(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder={`${low} — ${high}`}/><button onClick={()=>submit()}>确认</button></div></label></section></>}
    {stage==="boom"&&<section className="bomb-panel bomb-center boom-card"><img className="boom-main" src={`${process.env.NEXT_PUBLIC_BASE_PATH||""}/icons/cat-bomb/boom.png`} alt="BOOM 爆炸猫咪"/><small>炸弹数字是 {secret}</small><h1>{loser} 被炸成小黑炭啦！</h1><img className="charred-cat" src={`${process.env.NEXT_PUBLIC_BASE_PATH||""}/icons/cat-bomb/charred.png`} alt="被炸黑的猫咪"/><p>失败者可以选择真心话、大冒险，也可以安心跳过。</p><button className="primary full" onClick={()=>onTruthOrDare(loser)}>🎭 真心话 / 🎯 大冒险</button><button className="secondary full" onClick={onClose}>😊 跳过惩罚</button><button className="text-btn" onClick={reset}><RotateCcw/> 再来一局</button></section>}
  </div></div>
}
