"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Bookmark, Check, ChevronRight, Clock3, Dices, Heart, History, Home, Minus, Plus, RotateCcw, Search, Settings2, Shuffle, Sparkles, Trophy, Upload, UserRound, Users, X, Zap } from "lucide-react";
import { charadePacks, Game, games, Level, prompts, punishments, rewards } from "./cat-data";

type Tab = "home" | "games" | "tools" | "mine";
const DEFAULT_PLAYERS = ["小明", "小红", "阿杰", "圆圆"];

function useStored<T>(key:string, initial:T) {
  const [value,setValue]=useState(initial); const ready=useRef(false);
  useEffect(()=>{try{const saved=localStorage.getItem(key);if(saved)setValue(JSON.parse(saved))}catch{}ready.current=true},[key]);
  useEffect(()=>{if(ready.current)localStorage.setItem(key,JSON.stringify(value))},[key,value]);
  return [value,setValue] as const;
}

type CatVariant="gamepad"|"cards"|"party"|"support"|"heart"|"box"|"flag"|"sleep"|"search";
function CatIcon({variant,className=""}:{variant:CatVariant;className?:string}){
  const base=process.env.NEXT_PUBLIC_BASE_PATH||"";
  return <span className={`cat-sprite ${className}`} style={{backgroundImage:`url(${base}/icons/ui/${variant}.png)`}} role="img" aria-label="猫咪派对图标"/>;
}
function Cat({mood="happy",className=""}:{mood?:"happy"|"wink"|"party"|"sleep";className?:string}) {
  const variants:Record<NonNullable<typeof mood>,CatVariant>={happy:"heart",wink:"cards",party:"party",sleep:"sleep"};
  return <CatIcon variant={variants[mood]} className={`cat-doodle ${className}`}/>;
}
const GAME_ICON_IDS=["charades","undercover","turtle","garden","seven","never","story","dontdo","drawguess","telephone","likely","forehead","king","miss","oldmaid","bluff","truth","werewolf","bomb","randomchallenge"];
function GameCatIcon({game,className=""}:{game:Game;className?:string}){
  const base=process.env.NEXT_PUBLIC_BASE_PATH||"",id=GAME_ICON_IDS.includes(game.id)?game.id:"charades";
  return <span className={`game-icon-sprite ${className}`} style={{backgroundImage:`url(${base}/icons/games/${id}.png)`}} role="img" aria-label={`${game.name}猫咪图标`}/>;
}

export default function App(){
  const[tab,setTab]=useState<Tab>("home"),[detail,setDetail]=useState<Game|null>(null),[play,setPlay]=useState<Game|null>(null),[tool,setTool]=useState<string|null>(null);
  const[players,setPlayers]=useStored("party_players",DEFAULT_PLAYERS);const[favorites,setFavorites]=useStored<string[]>("party_favorites",[]);const[recent,setRecent]=useStored<string[]>("party_recent",[]);const[level,setLevel]=useStored<Level>("party_level","轻松");
  useEffect(()=>{if(!("serviceWorker"in navigator))return;if(process.env.NODE_ENV==="production"){navigator.serviceWorker.register(`${process.env.NEXT_PUBLIC_BASE_PATH||""}/sw.js`).catch(()=>{})}else{navigator.serviceWorker.getRegistrations().then(items=>items.forEach(item=>item.unregister()));if("caches"in window)caches.keys().then(keys=>Promise.all(keys.map(key=>caches.delete(key))))}},[]);
  const open=(g:Game)=>{setDetail(g);setRecent(r=>[g.id,...r.filter(x=>x!==g.id)].slice(0,8))};const start=(g:Game)=>{setDetail(null);setPlay(g);setRecent(r=>[g.id,...r.filter(x=>x!==g.id)].slice(0,8))};
  return <main><div className="ambient a1"/><div className="ambient a2"/><div className="paw-pattern"/><div className="app-shell">
    <header className="topbar"><button className="brand" onClick={()=>setTab("home")}><span className="brand-mark cat-logo"><i>•ᴗ•</i></span><span>猫咪派对<small>和好朋友，喵一晚</small></span></button><button className="avatar cat-avatar" onClick={()=>setTab("mine")}>ฅ</button></header>
    {tab==="home"&&<HomePage onTab={setTab} open={open} start={start} recent={recent}/>} {tab==="games"&&<GamesPage open={open}/>} {tab==="tools"&&<ToolsPage players={players} onTool={setTool}/>} {tab==="mine"&&<MinePage players={players} setPlayers={setPlayers} favorites={favorites} recent={recent} level={level} setLevel={setLevel} open={open}/>} 
  </div><nav className="bottom-nav cat-nav"><Nav active={tab==="home"} icon={<Home/>} label="首页" onClick={()=>setTab("home")}/><Nav active={tab==="games"} icon={<Search/>} label="找游戏" onClick={()=>setTab("games")}/><Nav active={tab==="tools"} icon={<Dices/>} label="百宝箱" onClick={()=>setTab("tools")}/><Nav active={tab==="mine"} icon={<UserRound/>} label="我的" onClick={()=>setTab("mine")}/></nav>
    {detail&&<Detail game={detail} favorite={favorites.includes(detail.id)} onFav={()=>setFavorites(f=>f.includes(detail.id)?f.filter(x=>x!==detail.id):[...f,detail.id])} onClose={()=>setDetail(null)} onStart={()=>start(detail)}/>} {play&&<Play game={play} players={players} level={level} onClose={()=>setPlay(null)}/>} {tool&&<Tool type={tool} players={players} level={level} onClose={()=>setTool(null)}/>} </main>
}
function Nav({active,icon,label,onClick}:{active:boolean;icon:React.ReactNode;label:string;onClick:()=>void}){return <button className={active?"active":""} onClick={onClick}>{icon}<span>{label}</span></button>}

function HomePage({onTab,open,start,recent}:{onTab:(t:Tab)=>void;open:(g:Game)=>void;start:(g:Game)=>void;recent:string[]}){
  const[pick,setPick]=useState<Game|null>(null);const featured=games.find(g=>g.id==="undercover")!;const quick=games.filter(g=>["charades","truth","turtle","king"].includes(g.id));const random=()=>setPick(games[Math.floor(Math.random()*games.length)]);
  return <div className="page home-page"><section className="hero cat-hero"><div className="hero-copy"><span className="eyebrow"><Sparkles/>猫猫今晚玩什么？</span><h1>朋友到齐，<br/><em>快乐开喵！</em></h1><p>一台手机，装下整场聚会的好玩点子。</p><div className="hero-actions"><button className="primary" onClick={()=>onTab("games")}><Search/>找个游戏</button><button className="secondary" onClick={random}><Shuffle/>猫猫帮选</button></div></div><div className="hero-art cat-stage"><span className="doodle-sun">☀</span><span className="doodle-fish">𓆝</span><span className="doodle-star">✦</span><Cat mood="party"/></div></section>
    <section><div className="section-head"><div><span className="eyebrow warm"><Zap/>马上开喵</span><h2>经典不冷场</h2></div><button onClick={()=>onTab("games")}>全部游戏 <ChevronRight/></button></div><div className="quick-grid">{quick.map(g=><GameCard key={g.id} game={g} onClick={()=>open(g)}/>)}</div></section>
    <section className="featured cat-featured"><div className="featured-icon"><Cat mood="wink"/><span>猫猫推荐</span></div><div><span className="meta">{featured.min}–{featured.max} 人 · {featured.minutes} 分钟</span><h2>{featured.name}</h2><p>{featured.tagline}</p><button onClick={()=>start(featured)}>直接开局 <ChevronRight/></button></div></section>
    {recent.length>0&&<section><div className="section-head"><div><span className="eyebrow"><History/>最近玩过</span><h2>再来一局喵</h2></div></div><div className="row-scroll">{recent.slice(0,4).map(id=>{const g=games.find(x=>x.id===id)!;return <MiniCard key={id} game={g} onClick={()=>open(g)}/>})}</div></section>}
    <section className="tool-teaser cat-teaser"><div><span>🐾 猫咪百宝箱</span><h2>抽签、分组、计时<br/>小事交给猫猫</h2><button onClick={()=>onTab("tools")}>打开百宝箱 <ChevronRight/></button></div><Cat mood="happy"/></section>
    {pick&&<div className="overlay"><div className="pick-dialog cat-dialog"><button className="close" onClick={()=>setPick(null)}><X/></button><Cat mood="wink"/><small>猫猫替你选好了</small><h2>{pick.name}</h2><p>{pick.tagline}</p><div className="tag-row"><span>{pick.min}–{pick.max} 人</span><span>{pick.minutes} 分钟</span></div><button className="primary full" onClick={()=>{setPick(null);open(pick)}}>就玩这个喵</button><button className="text-btn" onClick={random}><RotateCcw/>再选一次</button></div></div>}
  </div>
}
function GameCard({game,onClick}:{game:Game;onClick:()=>void}){return <button className={`game-card ${game.color}`} onClick={onClick}><span className="card-ears"/><GameCatIcon game={game} className="game-cat-icon"/><span className="level-pill">{game.level}</span><h3>{game.name}</h3><p>{game.tagline}</p><div><span><Users/>{game.min}–{game.max}</span><span><Clock3/>{game.minutes}′</span></div></button>}
function MiniCard({game,onClick}:{game:Game;onClick:()=>void}){return <button className="mini-card" onClick={onClick}><span className={`mini-icon ${game.color}`}><GameCatIcon game={game} className="mini-game-icon"/></span><span><b>{game.name}</b><small>{game.min}–{game.max} 人 · {game.minutes} 分钟</small></span><ChevronRight/></button>}

function GamesPage({open}:{open:(g:Game)=>void}){const[search,setSearch]=useState(""),[people,setPeople]=useState(0),[duration,setDuration]=useState(0),[req,setReq]=useState("全部"),[cat,setCat]=useState("全部");const filtered=useMemo(()=>games.filter(g=>(!search||g.name.includes(search)||g.tagline.includes(search))&&(!people||g.min<=people&&g.max>=people)&&(!duration||g.minutes<=duration)&&(req==="全部"||g.requirements.includes(req))&&(cat==="全部"||g.category===cat)),[search,people,duration,req,cat]);return <div className="page games-page"><Title eyebrow="猫猫游戏单" title="找个对味的" text="看看现场有几只猫，马上匹配合适玩法。"/><div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索游戏名称…"/></div><div className="filters"><Filter label="人数" values={["不限","4人","6人","8人","10人+"]} active={people?people>=10?"10人+":`${people}人`:"不限"} set={v=>setPeople(v==="不限"?0:parseInt(v))}/><Filter label="时长" values={["不限","15分钟","20分钟","30分钟"]} active={duration?`${duration}分钟`:"不限"} set={v=>setDuration(v==="不限"?0:parseInt(v))}/><Filter label="道具" values={["全部","无需道具","手机","纸笔","扑克牌"]} active={req} set={setReq}/><Filter label="类型" values={["全部","无道具","纸笔类","扑克牌","手机辅助"]} active={cat} set={setCat}/></div><div className="results-head"><b>找到 {filtered.length} 个游戏</b><button onClick={()=>{setPeople(0);setDuration(0);setReq("全部");setCat("全部")}}><RotateCcw/>重置</button></div><div className="catalog">{filtered.map(g=><GameCard key={g.id} game={g} onClick={()=>open(g)}/>)}</div>{!filtered.length&&<div className="empty"><Cat mood="sleep"/><h3>猫猫也没找到</h3><p>放宽一点条件试试看吧。</p></div>}</div>}
function Title({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="page-title"><span className="eyebrow"><Sparkles/>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>}
function Filter({label,values,active,set}:{label:string;values:string[];active:string;set:(v:string)=>void}){return <div className="filter-row"><b>{label}</b><div>{values.map(v=><button key={v} className={active===v?"on":""} onClick={()=>set(v)}>{v}</button>)}</div></div>}

const toolDefs=[{id:"wheel",name:"幸运转盘",desc:"转到谁就是谁",emoji:"🎡",color:"coral"},{id:"pick",name:"随机点名",desc:"公平选一只幸运猫",emoji:"☝️",color:"blue"},{id:"lots",name:"抽签盒",desc:"奖品惩罚一盒搞定",emoji:"🎟️",color:"amber"},{id:"cards",name:"奖惩卡片",desc:"翻开命运小卡片",emoji:"🃏",color:"violet"},{id:"teams",name:"随机分组",desc:"一键打乱公平组队",emoji:"👥",color:"green"},{id:"eliminate",name:"淘汰抽取",desc:"悬念留到最后",emoji:"🏆",color:"pink"},{id:"timer",name:"聚会计时器",desc:"倒计时滴答滴答",emoji:"⏱️",color:"teal"}];
function ToolCatIcon({id}:{id:string}){const base=process.env.NEXT_PUBLIC_BASE_PATH||"";return <span className="tool-icon-sprite" style={{backgroundImage:`url(${base}/icons/tools/${id}.png)`}} role="img" aria-label="百宝箱猫咪图标"/>}
function ToolsPage({players,onTool}:{players:string[];onTool:(s:string)=>void}){return <div className="page tools-page"><Title eyebrow="猫咪百宝箱" title="小工具，大快乐" text="不用下载，伸出猫爪点开就能用。"/><div className="player-status cat-status"><Cat mood="wink"/><div><b>本场玩家 · {players.length} 人</b><small>{players.join("、")||"还没有添加玩家"}</small></div></div><div className="tool-grid">{toolDefs.map(t=><button key={t.id} className={`tool-card ${t.color}`} onClick={()=>onTool(t.id)}><ToolCatIcon id={t.id}/><div><h3>{t.name}</h3><p>{t.desc}</p></div><ChevronRight/></button>)}</div><div className="safety-note"><Heart/><div><b>快乐有边界</b><p>所有惩罚都可以跳过或重抽，猫猫不勉强任何人。</p></div></div></div>}

function MinePage({players,setPlayers,favorites,recent,level,setLevel,open}:{players:string[];setPlayers:React.Dispatch<React.SetStateAction<string[]>>;favorites:string[];recent:string[];level:Level;setLevel:(l:Level)=>void;open:(g:Game)=>void}){const[name,setName]=useState("");const add=()=>{const n=name.trim();if(n&&!players.includes(n)){setPlayers(p=>[...p,n]);setName("")}};return <div className="page mine-page"><Title eyebrow="我的猫窝" title="人齐了，就开喵" text="名单和偏好只保存在你的设备上。"/><section className="panel"><div className="panel-head"><div><Users/><span><b>玩家名单</b><small>所有游戏与工具共用</small></span></div><strong>{players.length} 人</strong></div><div className="chips">{players.map((p,i)=><span key={`${p}${i}`}>{p}<button onClick={()=>setPlayers(x=>x.filter((_,j)=>j!==i))}><X/></button></span>)}</div><div className="add-player"><input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="输入玩家昵称"/><button onClick={add}><Plus/>添加</button></div></section><section className="panel"><div className="panel-head"><div><Settings2/><span><b>内容等级</b><small>题目和惩罚默认等级</small></span></div></div><div className="level-options">{(["轻松","熟人","刺激"]as Level[]).map(l=><button key={l} className={level===l?"on":""} onClick={()=>setLevel(l)}><span>{l==="轻松"?"🌿":l==="熟人"?"✨":"🔥"}</span><b>{l}</b><small>{l==="轻松"?"软乎乎":l==="熟人"?"更懂彼此":"大胆一点"}</small>{level===l&&<Check/>}</button>)}</div></section><ListSection title="我的收藏" icon={<Bookmark/>} ids={favorites} empty="喜欢的游戏会住在这里。" open={open}/><ListSection title="最近玩过" icon={<History/>} ids={recent} empty="还没有游戏脚印喵。" open={open}/><p className="privacy">🐾 无账号 · 无上传 · 数据仅存本机</p></div>}
function ListSection({title,icon,ids,empty,open}:{title:string;icon:React.ReactNode;ids:string[];empty:string;open:(g:Game)=>void}){return <section className="panel game-list"><div className="panel-head"><div>{icon}<span><b>{title}</b></span></div></div>{ids.length?ids.map(id=>{const g=games.find(x=>x.id===id);return g&&<MiniCard key={id} game={g} onClick={()=>open(g)}/>}):<p className="small-empty">{empty}</p>}</section>}

function Detail({game,favorite,onFav,onClose,onStart}:{game:Game;favorite:boolean;onFav:()=>void;onClose:()=>void;onStart:()=>void}){return <div className="sheet-overlay"><article className="detail-sheet"><div className={`detail-hero ${game.color}`}><div className="sheet-actions"><button onClick={onClose}><ArrowLeft/></button><button className={favorite?"fav on":"fav"} onClick={onFav}><Bookmark fill={favorite?"currentColor":"none"}/></button></div><GameCatIcon game={game} className="detail-cat-icon"/><span className="category">{game.category}</span><h1>{game.name}</h1><p>{game.tagline}</p><div className="detail-meta"><span><Users/>{game.min}–{game.max} 人</span><span><Clock3/>{game.minutes} 分钟</span><span><Zap/>{game.difficulty}</span></div></div><div className="detail-body"><section><h3>需要准备</h3><div className="requirement-row">{game.requirements.map(x=><span key={x}>🐾 {x}</span>)}</div></section><section><h3>怎么玩</h3><ol>{game.rules.map((r,i)=><li key={r}><span>{i+1}</span><p>{r}</p></li>)}</ol></section><section className="example"><b>举个例子</b><p>{game.example}</p></section><section><h3>胜利条件</h3><p>{game.victory}</p></section><section className="tip"><span>🐱</span><div><b>猫猫小贴士</b><p>{game.tip}</p></div></section></div><div className="sticky-action"><button className="primary full" onClick={onStart}>{game.tool?"马上开喵":"开始游戏"}<ChevronRight/></button></div></article></div>}

function Play({game,players,level,onClose}:{game:Game;players:string[];level:Level;onClose:()=>void}){if(game.id==="charades")return <Charades onClose={onClose}/>;if(game.tool==="identity")return <Identity game={game} players={players} onClose={onClose}/>;if(game.tool==="timer")return <TimerTool title={game.name} onClose={onClose}/>;return <Prompt game={game} players={players} level={level} onClose={onClose}/>}
function Charades({onClose}:{onClose:()=>void}){
  const[custom,setCustom]=useStored<string[]>("charades_custom_words",[]),[pack,setPack]=useState("family"),[draft,setDraft]=useState(""),[duration,setDuration]=useState(120),[remaining,setRemaining]=useState(120),[playing,setPlaying]=useState(false),[finished,setFinished]=useState(false),[words,setWords]=useState<string[]>([]),[index,setIndex]=useState(0),[correct,setCorrect]=useState(0),[skipped,setSkipped]=useState(0),[seen,setSeen]=useState(0),[confirmAdult,setConfirmAdult]=useState(false),[confirmExit,setConfirmExit]=useState(false);
  const selected=charadePacks.find(p=>p.id===pack);const allPacks=[...charadePacks,{id:"custom",name:"我的题库",emoji:"✍️",description:custom.length?`${custom.length} 个自定义词语`:"粘贴或导入自己的词语",adult:false,words:custom}];
  const parseWords=(text:string)=>Array.from(new Set(text.split(/[\n,，、;；\t]+/).map(x=>x.trim()).filter(Boolean))).slice(0,500);
  const importFile=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{const next=parseWords(String(reader.result||""));if(next.length){setCustom(next);setPack("custom")}};reader.readAsText(file)};
  const saveCustom=()=>{const next=parseWords(draft);if(next.length){setCustom(next);setPack("custom");setDraft("")}};
  const requestLandscape=async()=>{try{await document.documentElement.requestFullscreen?.();const orientation=screen.orientation as ScreenOrientation&{lock?:(mode:string)=>Promise<void>};await orientation.lock?.("landscape")}catch{}}
  const finishRound=()=>{setPlaying(false);setFinished(true)};
  useEffect(()=>{if(!playing||confirmExit)return;const timer=window.setInterval(()=>setRemaining(value=>{if(value<=1){window.clearInterval(timer);setTimeout(finishRound,0);return 0}return value-1}),1000);return()=>window.clearInterval(timer)},[playing,confirmExit]);
  const start=async()=>{const source=pack==="custom"?custom:selected?.words||[];if(!source.length)return;if(selected?.adult&&!confirmAdult){setConfirmAdult(true);return}setWords([...source].sort(()=>Math.random()-.5));setIndex(0);setCorrect(0);setSkipped(0);setSeen(0);setRemaining(duration);setFinished(false);setPlaying(true);await requestLandscape()};
  const answer=(right:boolean)=>{if(right)setCorrect(x=>x+1);else setSkipped(x=>x+1);setSeen(x=>x+1);if(index>=words.length-1){setWords(current=>[...current].sort(()=>Math.random()-.5));setIndex(0)}else setIndex(x=>x+1)};
  const exit=()=>{try{if(document.fullscreenElement)document.exitFullscreen()}catch{}onClose()};
  if(finished)return <div className="fullscreen charades-finish"><button className="charades-close" onClick={exit}><X/></button><Cat mood="party"/><span>{duration} 秒回合完成</span><h1>{correct} 题猜对！</h1><div><b>{seen}</b><small>已挑战</small><b>{skipped}</b><small>跳过</small></div><button className="primary big" onClick={start}><RotateCcw/>再来一局</button><button className="text-btn" onClick={()=>setFinished(false)}>更换题库或时间</button></div>;
  if(playing)return <div className="fullscreen charades-game"><button className="charades-close" aria-label="退出本轮" onClick={()=>setConfirmExit(true)}><X/></button><div className="charades-progress"><span className={remaining<=10?"urgent":""}><Clock3/>{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,"0")}</span><b><Trophy/>{correct}</b></div><button className="answer-zone correct-zone" onClick={()=>answer(true)}><Check/><span>猜对</span></button><div className="charades-word"><small>{allPacks.find(p=>p.id===pack)?.emoji} {allPacks.find(p=>p.id===pack)?.name}</small><h1>{words[index]}</h1><p>左边猜对 · 右边跳过</p></div><button className="answer-zone skip-zone" onClick={()=>answer(false)}><Shuffle/><span>跳过</span></button>{confirmExit&&<div className="exit-confirm" role="dialog" aria-modal="true" aria-labelledby="exit-title"><div className="exit-confirm-card"><span className="exit-cat">ฅ^•ﻌ•^ฅ</span><h2 id="exit-title">要退出这一轮吗？</h2><p>退出后本轮成绩不会保存，计时已为你暂停。</p><div><button className="secondary" onClick={()=>setConfirmExit(false)}>继续游戏</button><button className="exit-danger" onClick={exit}>确认退出</button></div></div></div>}</div>;
  return <div className="fullscreen charades-setup"><Head onClose={exit} title="🕺 你比划我来猜"/><div className="charades-setup-body"><div className="charades-title"><Cat mood="wink"/><div><span className="eyebrow"><Sparkles/>选择题库</span><h1>举起手机，马上开猜</h1><p>猜方拿着手机看词，对面的朋友负责比划。</p></div></div><div className="pack-grid">{allPacks.map(p=><button key={p.id} className={pack===p.id?"active":""} onClick={()=>setPack(p.id)}><span>{p.emoji}</span><div><b>{p.name}<i>{p.words.length} 词</i></b><small>{p.description}</small></div>{pack===p.id&&<Check/>}</button>)}</div><section className="round-time"><div><b>这一轮玩多久？</b><small>时间到后自动统计猜对题数</small></div><div>{[120,180,240,300].map(seconds=><button key={seconds} className={duration===seconds?"active":""} onClick={()=>setDuration(seconds)}><b>{seconds}</b><small>秒</small></button>)}</div></section><section className="custom-pack"><div><b>导入自己的题库</b><small>每行一个词，也支持逗号分隔；最多 500 个。</small></div><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder={"例如：\n跳绳\n吃火锅\n小猫钓鱼"}/><div><label className="secondary"><Upload/>选择 TXT 文件<input type="file" accept=".txt,.csv,text/plain" onChange={e=>importFile(e.target.files?.[0])}/></label><button className="secondary" disabled={!parseWords(draft).length} onClick={saveCustom}><Plus/>保存为我的题库</button></div></section>{confirmAdult&&<div className="adult-confirm"><span>🔞</span><div><b>确认所有玩家均已成年</b><p>18 禁题库只适合自愿参与的成年人，任何题目都可以跳过。</p></div><button onClick={()=>{setConfirmAdult(false);setTimeout(start,0)}}>确认进入</button></div>}<button className="primary charades-start" disabled={pack==="custom"&&!custom.length} onClick={start}><Sparkles/>开始 {duration} 秒回合</button><p className="rotate-hint">📱 开始后请横拿手机，点击屏幕左右两侧操作</p></div></div>
}
function Prompt({game,players,level,onClose}:{game:Game;players:string[];level:Level;onClose:()=>void}){const pool=prompts[game.id]||prompts.randomchallenge;const[used,setUsed]=useState<number[]>([]),[idx,setIdx]=useState<number|null>(null),[person,setPerson]=useState("");const draw=()=>{let left=pool.map((_,i)=>i).filter(i=>!used.includes(i));if(!left.length){setUsed([]);left=pool.map((_,i)=>i)}const n=left[Math.floor(Math.random()*left.length)];setIdx(n);setUsed(x=>[...x,n]);if(players.length)setPerson(players[Math.floor(Math.random()*players.length)])};return <div className="fullscreen play-screen"><Head onClose={onClose} title={`${game.emoji} ${game.name}`}/><div className="play-content">{idx===null?<><Cat mood="party"/><h1>准备好了吗？</h1><p>{pool.length} 张题卡 · {level}模式</p><button className="primary big" onClick={draw}><Sparkles/>抽一张</button></>:<><span className="turn-label">{person&&`${person} 的题目`}</span><div className="prompt-card"><small>第 {used.length} 题</small><h1>{pool[idx]}</h1><span>不舒服可以跳过，开心最重要</span></div><div className="play-buttons"><button className="secondary" onClick={draw}><Shuffle/>跳过</button><button className="primary" onClick={draw}><Check/>完成，下一题</button></div></>}</div></div>}
function Identity({game,players,onClose}:{game:Game;players:string[];onClose:()=>void}){const[roles,setRoles]=useState<string[]>([]),[index,setIndex]=useState(0),[show,setShow]=useState(false),[done,setDone]=useState(false);const begin=()=>{let r:string[]=[];if(game.id==="undercover"){const pair=[["牛奶","豆浆"],["橙子","橘子"],["饺子","馄饨"]][Math.floor(Math.random()*3)];r=players.map(()=>pair[0]);r[Math.floor(Math.random()*players.length)]=pair[1]}else if(game.id==="dontdo"){r=["不能说我","不能摸头发","不能回答是","不能叫别人名字","不能看时间","不能翘腿"].slice(0,players.length).sort(()=>Math.random()-.5)}else{const w=players.length>=9?3:2;r=[...Array(w).fill("狼人"),"预言家","女巫",...Array(Math.max(0,players.length-w-2)).fill("村民")].sort(()=>Math.random()-.5)}setRoles(r)};if(!roles.length)return <div className="fullscreen identity-screen"><Head onClose={onClose} title={`${game.emoji} 身份准备`}/><div className="identity-intro"><Cat mood="wink"/><h1>秘密传阅喵</h1><p>每个人只看自己的身份，看完藏好再交给下一位。</p><div className="player-preview">{players.map((p,i)=><span key={p}><i>{i+1}</i>{p}</span>)}</div>{players.length>=game.min?<button className="primary big" onClick={begin}>开始分配身份</button>:<div className="warning">至少需要 {game.min} 位玩家。</div>}</div></div>;if(done)return <div className="fullscreen identity-screen"><Head onClose={onClose} title={game.name}/><div className="identity-intro"><Cat mood="party"/><h1>身份分配完成</h1><p>把手机交给主持人，游戏开始喵！</p><button className="primary big" onClick={onClose}>进入讨论</button></div></div>;const next=()=>{setShow(false);if(index===players.length-1)setDone(true);else setIndex(i=>i+1)};return <div className="fullscreen identity-screen"><Head onClose={onClose} title={`${index+1} / ${players.length}`}/><div className="identity-pass"><span className="turn-label">请把手机交给</span><h1>{players[index]}</h1>{show?<><div className="role-card"><small>你的身份 / 词语是</small><h2>{roles[index]}</h2><p>记住秘密，不要让别人看见</p></div><button className="primary big" onClick={next}>记住了，藏好并传递</button></>:<><div className="hidden-card"><Cat mood="sleep"/><b>秘密藏好啦</b><small>确认周围没有偷看的猫</small></div><button className="primary big" onClick={()=>setShow(true)}>查看我的身份</button></>}</div></div>}
function Head({onClose,title}:{onClose:()=>void;title:string}){return <div className="play-head"><button onClick={onClose}><X/></button><span>{title}</span></div>}

function Tool({type,players,level,onClose}:{type:string;players:string[];level:Level;onClose:()=>void}){if(type==="timer")return <TimerTool title="猫咪计时器" onClose={onClose}/>;if(type==="teams")return <Teams players={players} onClose={onClose}/>;return <Draw type={type} players={players} level={level} onClose={onClose}/>}
function TimerTool({title,onClose}:{title:string;onClose:()=>void}){const[sec,setSec]=useState(60),[left,setLeft]=useState(60),[run,setRun]=useState(false);useEffect(()=>{if(!run)return;const id=setInterval(()=>setLeft(x=>x<=1?(setRun(false),0):x-1),1000);return()=>clearInterval(id)},[run]);return <div className="fullscreen timer-screen"><Head onClose={onClose} title={`⏱️ ${title}`}/><div className="timer-content"><Cat mood={left===0?"party":"happy"}/><div className={`timer-ring ${run?"ticking":""}`}><small>{left?"剩余时间":"时间到喵！"}</small><b>{Math.floor(left/60).toString().padStart(2,"0")}:{(left%60).toString().padStart(2,"0")}</b></div><div className="preset-row">{[30,60,90,120].map(s=><button key={s} className={sec===s?"on":""} onClick={()=>{setSec(s);setLeft(s);setRun(false)}}>{s<60?`${s}秒`:`${s/60}分钟`}</button>)}</div><button className="primary big" onClick={()=>left?setRun(x=>!x):(setLeft(sec),setRun(true))}>{run?"暂停":"开始计时"}</button></div></div>}
function Draw({type,players,level,onClose}:{type:string;players:string[];level:Level;onClose:()=>void}){const[kind,setKind]=useState<"玩家"|"奖励"|"惩罚">(type==="pick"||type==="eliminate"?"玩家":type==="cards"?"惩罚":"玩家"),[result,setResult]=useState(""),[history,setHistory]=useState<string[]>([]),[out,setOut]=useState<string[]>([]);const[custom,setCustom]=useStored<string[]>("party_custom_draw",[]),[input,setInput]=useState("");const source=kind==="玩家"?players:kind==="奖励"?[...rewards,...custom]:[...punishments[level],...custom];const available=type==="eliminate"?source.filter(x=>!out.includes(x)):source;const draw=()=>{if(!available.length)return;const r=available[Math.floor(Math.random()*available.length)];setResult(r);setHistory(h=>[r,...h]);if(type==="eliminate")setOut(o=>[...o,r])};const name:{[k:string]:string}={wheel:"幸运转盘",pick:"随机点名",lots:"抽签盒",cards:"奖惩卡片",eliminate:"淘汰抽取"};return <div className="fullscreen draw-screen"><Head onClose={onClose} title={`🐾 ${name[type]}`}/><div className="draw-content"><div className="segmented">{(["玩家","奖励","惩罚"]as const).map(k=><button key={k} className={kind===k?"on":""} onClick={()=>{setKind(k);setResult("")}}>{k}</button>)}</div>{result?<div className="draw-result cat-result"><Cat mood="party"/><small>{kind==="玩家"?"猫猫选中了":"抽取结果"}</small><h1>{result}</h1></div>:<div className="draw-placeholder"><Cat mood="wink"/><h2>{source.length} 个选项准备好了</h2></div>}<button className="primary big" disabled={!available.length} onClick={draw}><Sparkles/>{result?"再抽一次":"开始抽取"}</button>{result&&kind==="惩罚"&&<button className="secondary big" onClick={()=>setResult("本轮免罚 ✨")}><Heart/>本轮免罚</button>}<div className="custom-add"><input value={input} onChange={e=>setInput(e.target.value)} placeholder="添加自定义奖品或惩罚"/><button onClick={()=>{if(input.trim()){setCustom(c=>[...c,input.trim()]);setInput("")}}}><Plus/></button></div>{history.length>0&&<div className="history-list"><b>本轮记录</b>{history.map((h,i)=><span key={`${h}${i}`}><small>{history.length-i}</small>{h}</span>)}</div>}</div></div>}
function Teams({players,onClose}:{players:string[];onClose:()=>void}){const[count,setCount]=useState(2),[teams,setTeams]=useState<string[][]>([]);const make=()=>{const s=[...players].sort(()=>Math.random()-.5),t=Array.from({length:Math.min(count,players.length)},()=>[]as string[]);s.forEach((p,i)=>t[i%t.length].push(p));setTeams(t)};return <div className="fullscreen draw-screen"><Head onClose={onClose} title="🐾 随机分组"/><div className="draw-content"><Cat mood="happy"/><div className="stepper"><button onClick={()=>setCount(c=>Math.max(2,c-1))}><Minus/></button><div><b>{count}</b><span>组</span></div><button onClick={()=>setCount(c=>Math.min(Math.max(2,players.length),c+1))}><Plus/></button></div>{teams.length>0&&<div className="teams-result">{teams.map((t,i)=><div key={i}><b>第 {i+1} 组</b>{t.map(p=><span key={p}>{p}</span>)}</div>)}</div>}<button className="primary big" disabled={players.length<2} onClick={make}><Shuffle/>{teams.length?"重新分组":"开始分组"}</button></div></div>}
