"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Bookmark, Check, ChevronRight, Clock3, Dices, Heart, History, Home, Minus, Plus, RotateCcw, Search, Settings2, Shuffle, Sparkles, Trophy, Upload, UserRound, Users, X, Zap } from "lucide-react";
import { charadePacks, Game, games, Level, prompts, punishments, rewards } from "./cat-data";
import { truthQuestionSeeds } from "./truth-data";

type Tab = "home" | "games" | "tools" | "mine";
const DEFAULT_PLAYERS = ["小明", "小红", "阿杰", "圆圆"];

function useStored<T>(key:string, initial:T) {
  const [value,setValue]=useState(initial),[hydrated,setHydrated]=useState(false);
  useEffect(()=>{try{const saved=localStorage.getItem(key);if(saved)setValue(JSON.parse(saved))}catch{}setHydrated(true)},[key]);
  useEffect(()=>{if(hydrated)localStorage.setItem(key,JSON.stringify(value))},[key,value,hydrated]);
  return [value,setValue] as const;
}

type CatVariant="gamepad"|"cards"|"party"|"support"|"heart"|"box"|"flag"|"sleep"|"search";
function CatIcon({variant,className=""}:{variant:CatVariant;className?:string}){
  const base=process.env.NEXT_PUBLIC_BASE_PATH||"";
  return <span className={`cat-sprite ${className}`} style={{backgroundImage:`url(${base}/icons/ui/${variant}.png)`}} role="img" aria-label="猫咪派对图标"/>;
}
function Cat({mood="happy",className=""}:{mood?:"happy"|"wink"|"party"|"sleep";className?:string}) {
  const variants:Record<NonNullable<typeof mood>,CatVariant>={happy:"heart",wink:"cards",party:"party",sleep:"sleep"};
  return <CatIcon variant={variants[mood]} className={`cat-doodle ${className}`}/>;
}
const GAME_ICON_IDS=["charades","undercover","turtle","garden","seven","never","story","dontdo","drawguess","telephone","likely","forehead","king","miss","oldmaid","bluff","truth","werewolf","bomb","randomchallenge"];
function GameCatIcon({game,className=""}:{game:Game;className?:string}){
  const base=process.env.NEXT_PUBLIC_BASE_PATH||"",id=GAME_ICON_IDS.includes(game.id)?game.id:"charades";
  return <span className={`game-icon-sprite ${className}`} style={{backgroundImage:`url(${base}/icons/games/${id}.png)`}} role="img" aria-label={`${game.name}猫咪图标`}/>;
}
const gameTime=(game:Game)=>game.durationLabel||String(game.minutes);

export default function App(){
  const[tab,setTab]=useState<Tab>("home"),[detail,setDetail]=useState<Game|null>(null),[play,setPlay]=useState<Game|null>(null),[tool,setTool]=useState<string|null>(null);
  const[players,setPlayers]=useStored("party_players",DEFAULT_PLAYERS);const[favorites,setFavorites]=useStored<string[]>("party_favorites",[]);const[recent,setRecent]=useStored<string[]>("party_recent",[]);const[level,setLevel]=useStored<Level>("party_level","轻松");
  useEffect(()=>{if(!("serviceWorker"in navigator))return;if(process.env.NODE_ENV==="production"){navigator.serviceWorker.register(`${process.env.NEXT_PUBLIC_BASE_PATH||""}/sw.js`).catch(()=>{})}else{navigator.serviceWorker.getRegistrations().then(items=>items.forEach(item=>item.unregister()));if("caches"in window)caches.keys().then(keys=>Promise.all(keys.map(key=>caches.delete(key))))}},[]);
  const open=(g:Game)=>{setDetail(g);setRecent(r=>[g.id,...r.filter(x=>x!==g.id)].slice(0,8))};const start=(g:Game)=>{setDetail(null);setPlay(g);setRecent(r=>[g.id,...r.filter(x=>x!==g.id)].slice(0,8))};
  return <main><div className="ambient a1"/><div className="ambient a2"/><div className="paw-pattern"/><div className="app-shell">
    <header className="topbar"><button className="brand" onClick={()=>setTab("home")}><span className="brand-mark cat-logo"><i>•ᴗ•</i></span><span>猫咪派对<small>和好朋友，喵一晚</small></span></button><button className="avatar cat-avatar" onClick={()=>setTab("mine")}>ฅ</button></header>
    {tab==="home"&&<HomePage onTab={setTab} open={open} start={start} recent={recent}/>} {tab==="games"&&<GamesPage open={open}/>} {tab==="tools"&&<ToolsPage players={players} onTool={setTool}/>} {tab==="mine"&&<MinePage players={players} setPlayers={setPlayers} favorites={favorites} recent={recent} level={level} setLevel={setLevel} open={open}/>} 
  </div><nav className="bottom-nav cat-nav"><Nav active={tab==="home"} icon={<Home/>} label="首页" onClick={()=>setTab("home")}/><Nav active={tab==="games"} icon={<Search/>} label="找游戏" onClick={()=>setTab("games")}/><Nav active={tab==="tools"} icon={<Dices/>} label="百宝箱" onClick={()=>setTab("tools")}/><Nav active={tab==="mine"} icon={<UserRound/>} label="我的" onClick={()=>setTab("mine")}/></nav>
    {detail&&<Detail game={detail} favorite={favorites.includes(detail.id)} onFav={()=>setFavorites(f=>f.includes(detail.id)?f.filter(x=>x!==detail.id):[...f,detail.id])} onClose={()=>setDetail(null)} onStart={()=>start(detail)}/>} {play&&<Play game={play} players={players} level={level} onClose={()=>setPlay(null)}/>} {tool&&<Tool type={tool} players={players} level={level} onClose={()=>setTool(null)}/>} </main>
}
function Nav({active,icon,label,onClick}:{active:boolean;icon:React.ReactNode;label:string;onClick:()=>void}){return <button className={active?"active":""} onClick={onClick}>{icon}<span>{label}</span></button>}

function HomePage({onTab,open,start,recent}:{onTab:(t:Tab)=>void;open:(g:Game)=>void;start:(g:Game)=>void;recent:string[]}){
  const[pick,setPick]=useState<Game|null>(null);const featured=games.find(g=>g.id==="undercover")!;const quick=games.filter(g=>["charades","truth","turtle","king"].includes(g.id));const random=()=>setPick(games[Math.floor(Math.random()*games.length)]);
  return <div className="page home-page"><section className="hero cat-hero"><div className="hero-copy"><span className="eyebrow"><Sparkles/>猫猫今晚玩什么？</span><h1>朋友到齐，<br/><em>快乐开喵！</em></h1><p>一台手机，装下整场聚会的好玩点子。</p><div className="hero-actions"><button className="primary" onClick={()=>onTab("games")}><Search/>找个游戏</button><button className="secondary" onClick={random}><Shuffle/>猫猫帮选</button></div></div><div className="hero-art cat-stage"><span className="doodle-sun">☀</span><span className="doodle-fish">𓆝</span><span className="doodle-star">✦</span><Cat mood="party"/></div></section>
    <section><div className="section-head"><div><span className="eyebrow warm"><Zap/>马上开喵</span><h2>经典不冷场</h2></div><button onClick={()=>onTab("games")}>全部游戏 <ChevronRight/></button></div><div className="quick-grid">{quick.map(g=><GameCard key={g.id} game={g} onClick={()=>open(g)}/>)}</div></section>
    <section className="featured cat-featured"><div className="featured-icon"><Cat mood="wink"/><span>猫猫推荐</span></div><div><span className="meta">{featured.min}–{featured.max} 人 · {gameTime(featured)} 分钟</span><h2>{featured.name}</h2><p>{featured.tagline}</p><button onClick={()=>start(featured)}>直接开局 <ChevronRight/></button></div></section>
    {recent.length>0&&<section><div className="section-head"><div><span className="eyebrow"><History/>最近玩过</span><h2>再来一局喵</h2></div></div><div className="row-scroll">{recent.slice(0,4).map(id=>{const g=games.find(x=>x.id===id)!;return <MiniCard key={id} game={g} onClick={()=>open(g)}/>})}</div></section>}
    <section className="tool-teaser cat-teaser"><div><span>🐾 猫咪百宝箱</span><h2>抽签、分组、计时<br/>小事交给猫猫</h2><button onClick={()=>onTab("tools")}>打开百宝箱 <ChevronRight/></button></div><Cat mood="happy"/></section>
    {pick&&<div className="overlay"><div className="pick-dialog cat-dialog"><button className="close" onClick={()=>setPick(null)}><X/></button><Cat mood="wink"/><small>猫猫替你选好了</small><h2>{pick.name}</h2><p>{pick.tagline}</p><div className="tag-row"><span>{pick.min}–{pick.max} 人</span><span>{gameTime(pick)} 分钟</span></div><button className="primary full" onClick={()=>{setPick(null);open(pick)}}>就玩这个喵</button><button className="text-btn" onClick={random}><RotateCcw/>再选一次</button></div></div>}
  </div>
}
function GameCard({game,onClick}:{game:Game;onClick:()=>void}){return <button className={`game-card ${game.color}`} onClick={onClick}><span className="card-ears"/><GameCatIcon game={game} className="game-cat-icon"/><span className="level-pill">{game.level}</span><h3>{game.name}</h3><p>{game.tagline}</p><div><span><Users/>{game.min}–{game.max}</span><span><Clock3/>{gameTime(game)}′</span></div></button>}
function MiniCard({game,onClick}:{game:Game;onClick:()=>void}){return <button className="mini-card" onClick={onClick}><span className={`mini-icon ${game.color}`}><GameCatIcon game={game} className="mini-game-icon"/></span><span><b>{game.name}</b><small>{game.min}–{game.max} 人 · {gameTime(game)} 分钟</small></span><ChevronRight/></button>}

function GamesPage({open}:{open:(g:Game)=>void}){const[search,setSearch]=useState(""),[people,setPeople]=useState(0),[duration,setDuration]=useState(0),[req,setReq]=useState("全部"),[cat,setCat]=useState("全部");const filtered=useMemo(()=>games.filter(g=>(!search||g.name.includes(search)||g.tagline.includes(search))&&(!people||g.min<=people&&g.max>=people)&&(!duration||g.minutes<=duration)&&(req==="全部"||g.requirements.includes(req))&&(cat==="全部"||g.category===cat)),[search,people,duration,req,cat]);return <div className="page games-page"><Title eyebrow="猫猫游戏单" title="找个对味的" text="看看现场有几只猫，马上匹配合适玩法。"/><div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索游戏名称…"/></div><div className="filters"><Filter label="人数" values={["不限","4人","6人","8人","10人+"]} active={people?people>=10?"10人+":`${people}人`:"不限"} set={v=>setPeople(v==="不限"?0:parseInt(v))}/><Filter label="时长" values={["不限","15分钟","20分钟","30分钟"]} active={duration?`${duration}分钟`:"不限"} set={v=>setDuration(v==="不限"?0:parseInt(v))}/><Filter label="道具" values={["全部","无需道具","手机","纸笔","扑克牌"]} active={req} set={setReq}/><Filter label="类型" values={["全部","无道具","纸笔类","扑克牌","手机辅助"]} active={cat} set={setCat}/></div><div className="results-head"><b>找到 {filtered.length} 个游戏</b><button onClick={()=>{setPeople(0);setDuration(0);setReq("全部");setCat("全部")}}><RotateCcw/>重置</button></div><div className="catalog">{filtered.map(g=><GameCard key={g.id} game={g} onClick={()=>open(g)}/>)}</div>{!filtered.length&&<div className="empty"><Cat mood="sleep"/><h3>猫猫也没找到</h3><p>放宽一点条件试试看吧。</p></div>}</div>}
function Title({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="page-title"><span className="eyebrow"><Sparkles/>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>}
function Filter({label,values,active,set}:{label:string;values:string[];active:string;set:(v:string)=>void}){return <div className="filter-row"><b>{label}</b><div>{values.map(v=><button key={v} className={active===v?"on":""} onClick={()=>set(v)}>{v}</button>)}</div></div>}

const toolDefs=[{id:"blindbox",name:"小猫盲盒",desc:"全站共用的道具与状态卡",emoji:"🎁",color:"pink"},{id:"wheel",name:"幸运转盘",desc:"转到谁就是谁",emoji:"🎡",color:"coral"},{id:"pick",name:"随机点名",desc:"公平选一只幸运猫",emoji:"☝️",color:"blue"},{id:"lots",name:"抽签盒",desc:"奖品惩罚一盒搞定",emoji:"🎟️",color:"amber"},{id:"cards",name:"奖惩卡片",desc:"翻开命运小卡片",emoji:"🃏",color:"violet"},{id:"teams",name:"随机分组",desc:"一键打乱公平组队",emoji:"👥",color:"green"},{id:"eliminate",name:"淘汰抽取",desc:"悬念留到最后",emoji:"🏆",color:"pink"},{id:"timer",name:"聚会计时器",desc:"倒计时滴答滴答",emoji:"⏱️",color:"teal"}];
function ToolCatIcon({id}:{id:string}){const base=process.env.NEXT_PUBLIC_BASE_PATH||"";return <span className="tool-icon-sprite" style={{backgroundImage:`url(${base}/icons/tools/${id}.png)`}} role="img" aria-label="百宝箱猫咪图标"/>}
function ToolsPage({players,onTool}:{players:string[];onTool:(s:string)=>void}){return <div className="page tools-page"><Title eyebrow="猫咪百宝箱" title="小工具，大快乐" text="不用下载，伸出猫爪点开就能用。"/><div className="player-status cat-status"><Cat mood="wink"/><div><b>本场玩家 · {players.length} 人</b><small>{players.join("、")||"还没有添加玩家"}</small></div></div><div className="tool-grid">{toolDefs.map(t=><button key={t.id} className={`tool-card ${t.color}`} onClick={()=>onTool(t.id)}><ToolCatIcon id={t.id}/><div><h3>{t.name}</h3><p>{t.desc}</p></div><ChevronRight/></button>)}</div><div className="safety-note"><Heart/><div><b>快乐有边界</b><p>所有惩罚都可以跳过或重抽，猫猫不勉强任何人。</p></div></div></div>}

function MinePage({players,setPlayers,favorites,recent,level,setLevel,open}:{players:string[];setPlayers:React.Dispatch<React.SetStateAction<string[]>>;favorites:string[];recent:string[];level:Level;setLevel:(l:Level)=>void;open:(g:Game)=>void}){const[name,setName]=useState("");const add=()=>{const n=name.trim();if(n&&!players.includes(n)){setPlayers(p=>[...p,n]);setName("")}};return <div className="page mine-page"><Title eyebrow="我的猫窝" title="人齐了，就开喵" text="名单和偏好只保存在你的设备上。"/><section className="panel"><div className="panel-head"><div><Users/><span><b>玩家名单</b><small>所有游戏与工具共用</small></span></div><strong>{players.length} 人</strong></div><div className="chips">{players.map((p,i)=><span key={`${p}${i}`}>{p}<button onClick={()=>setPlayers(x=>x.filter((_,j)=>j!==i))}><X/></button></span>)}</div><div className="add-player"><input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="输入玩家昵称"/><button onClick={add}><Plus/>添加</button></div></section><section className="panel"><div className="panel-head"><div><Settings2/><span><b>内容等级</b><small>题目和惩罚默认等级</small></span></div></div><div className="level-options">{(["轻松","熟人","刺激"]as Level[]).map(l=><button key={l} className={level===l?"on":""} onClick={()=>setLevel(l)}><span>{l==="轻松"?"🌿":l==="熟人"?"✨":"🔥"}</span><b>{l}</b><small>{l==="轻松"?"软乎乎":l==="熟人"?"更懂彼此":"大胆一点"}</small>{level===l&&<Check/>}</button>)}</div></section><ListSection title="我的收藏" icon={<Bookmark/>} ids={favorites} empty="喜欢的游戏会住在这里。" open={open}/><ListSection title="最近玩过" icon={<History/>} ids={recent} empty="还没有游戏脚印喵。" open={open}/><p className="privacy">🐾 无账号 · 无上传 · 数据仅存本机</p></div>}
function ListSection({title,icon,ids,empty,open}:{title:string;icon:React.ReactNode;ids:string[];empty:string;open:(g:Game)=>void}){return <section className="panel game-list"><div className="panel-head"><div>{icon}<span><b>{title}</b></span></div></div>{ids.length?ids.map(id=>{const g=games.find(x=>x.id===id);return g&&<MiniCard key={id} game={g} onClick={()=>open(g)}/>}):<p className="small-empty">{empty}</p>}</section>}

function Detail({game,favorite,onFav,onClose,onStart}:{game:Game;favorite:boolean;onFav:()=>void;onClose:()=>void;onStart:()=>void}){return <div className="sheet-overlay"><article className="detail-sheet"><div className={`detail-hero ${game.color}`}><div className="sheet-actions"><button onClick={onClose}><ArrowLeft/></button><button className={favorite?"fav on":"fav"} onClick={onFav}><Bookmark fill={favorite?"currentColor":"none"}/></button></div><GameCatIcon game={game} className="detail-cat-icon"/><span className="category">{game.category}</span><h1>{game.name}</h1><p>{game.tagline}</p><div className="detail-meta"><span><Users/>{game.min}–{game.max} 人</span><span><Clock3/>{gameTime(game)} 分钟</span><span><Zap/>{game.difficulty}</span></div></div><div className="detail-body"><section><h3>需要准备</h3><div className="requirement-row">{game.requirements.map(x=><span key={x}>🐾 {x}</span>)}</div></section><section><h3>怎么玩</h3><ol>{game.rules.map((r,i)=><li key={r}><span>{i+1}</span><p>{r}</p></li>)}</ol></section><section className="example"><b>举个例子</b><p>{game.example}</p></section><section><h3>胜利条件</h3><p>{game.victory}</p></section><section className="tip"><span>🐱</span><div><b>猫猫小贴士</b><p>{game.tip}</p></div></section></div><div className="sticky-action"><button className="primary full" onClick={onStart}>{game.tool?"马上开喵":"开始游戏"}<ChevronRight/></button></div></article></div>}

function Play({game,players,level,onClose}:{game:Game;players:string[];level:Level;onClose:()=>void}){if(game.id==="charades")return <Charades onClose={onClose}/>;if(game.id==="truth")return <TruthOrDare players={players} onClose={onClose}/>;if(game.tool==="identity")return <Identity game={game} players={players} onClose={onClose}/>;if(game.tool==="timer")return <TimerTool title={game.name} onClose={onClose}/>;return <Prompt game={game} players={players} level={level} onClose={onClose}/>}
function Charades({onClose}:{onClose:()=>void}){
  const[custom,setCustom]=useStored<string[]>("charades_custom_words",[]),[pack,setPack]=useState("family"),[draft,setDraft]=useState(""),[duration,setDuration]=useState(120),[remaining,setRemaining]=useState(120),[playing,setPlaying]=useState(false),[finished,setFinished]=useState(false),[words,setWords]=useState<string[]>([]),[index,setIndex]=useState(0),[correct,setCorrect]=useState(0),[skipped,setSkipped]=useState(0),[seen,setSeen]=useState(0),[confirmAdult,setConfirmAdult]=useState(false),[confirmExit,setConfirmExit]=useState(false);
  const selected=charadePacks.find(p=>p.id===pack);const allPacks=[...charadePacks,{id:"custom",name:"我的题库",emoji:"✍️",description:custom.length?`${custom.length} 个自定义词语`:"粘贴或导入自己的词语",adult:false,words:custom}];
  const parseWords=(text:string)=>Array.from(new Set(text.split(/[\n,，、;；\t]+/).map(x=>x.trim()).filter(Boolean))).slice(0,500);
  const importFile=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{const next=parseWords(String(reader.result||""));if(next.length){setCustom(next);setPack("custom")}};reader.readAsText(file)};
  const saveCustom=()=>{const next=parseWords(draft);if(next.length){setCustom(next);setPack("custom");setDraft("")}};
  const requestLandscape=async()=>{try{await document.documentElement.requestFullscreen?.();const orientation=screen.orientation as ScreenOrientation&{lock?:(mode:string)=>Promise<void>};await orientation.lock?.("landscape")}catch{}}
  const finishRound=()=>{setPlaying(false);setFinished(true)};
  useEffect(()=>{if(!playing||confirmExit)return;const timer=window.setInterval(()=>setRemaining(value=>{if(value<=1){window.clearInterval(timer);setTimeout(finishRound,0);return 0}return value-1}),1000);return()=>window.clearInterval(timer)},[playing,confirmExit]);
  const start=async()=>{const source=pack==="custom"?custom:selected?.words||[];if(!source.length)return;if(selected?.adult&&!confirmAdult){setConfirmAdult(true);return}setWords([...source].sort(()=>Math.random()-.5));setIndex(0);setCorrect(0);setSkipped(0);setSeen(0);setRemaining(duration);setFinished(false);setPlaying(true);await requestLandscape()};
  const answer=(right:boolean)=>{if(right)setCorrect(x=>x+1);else setSkipped(x=>x+1);setSeen(x=>x+1);if(index>=words.length-1){setWords(current=>[...current].sort(()=>Math.random()-.5));setIndex(0)}else setIndex(x=>x+1)};
  const exit=()=>{try{if(document.fullscreenElement)document.exitFullscreen()}catch{}onClose()};
  if(finished)return <div className="fullscreen charades-finish"><button className="charades-close" onClick={exit}><X/></button><Cat mood="party"/><span>{duration} 秒回合完成</span><h1>{correct} 题猜对！</h1><div><b>{seen}</b><small>已挑战</small><b>{skipped}</b><small>跳过</small></div><button className="primary big" onClick={start}><RotateCcw/>再来一局</button><button className="text-btn" onClick={()=>setFinished(false)}>更换题库或时间</button></div>;
  if(playing)return <div className="fullscreen charades-game"><button className="charades-close" aria-label="退出本轮" onClick={()=>setConfirmExit(true)}><X/></button><div className="charades-progress"><span className={remaining<=10?"urgent":""}><Clock3/>{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,"0")}</span><b><Trophy/>{correct}</b></div><button className="answer-zone correct-zone" onClick={()=>answer(true)}><Check/><span>猜对</span></button><div className="charades-word"><small>{allPacks.find(p=>p.id===pack)?.emoji} {allPacks.find(p=>p.id===pack)?.name}</small><h1>{words[index]}</h1><p>左边猜对 · 右边跳过</p></div><button className="answer-zone skip-zone" onClick={()=>answer(false)}><Shuffle/><span>跳过</span></button>{confirmExit&&<div className="exit-confirm" role="dialog" aria-modal="true" aria-labelledby="exit-title"><div className="exit-confirm-card"><span className="exit-cat">ฅ^•ﻌ•^ฅ</span><h2 id="exit-title">要退出这一轮吗？</h2><p>退出后本轮成绩不会保存，计时已为你暂停。</p><div><button className="secondary" onClick={()=>setConfirmExit(false)}>继续游戏</button><button className="exit-danger" onClick={exit}>确认退出</button></div></div></div>}</div>;
  return <div className="fullscreen charades-setup"><Head onClose={exit} title="🕺 你比划我来猜"/><div className="charades-setup-body"><div className="charades-title"><Cat mood="wink"/><div><span className="eyebrow"><Sparkles/>选择题库</span><h1>举起手机，马上开猜</h1><p>猜方拿着手机看词，对面的朋友负责比划。</p></div></div><div className="pack-grid">{allPacks.map(p=><button key={p.id} className={pack===p.id?"active":""} onClick={()=>setPack(p.id)}><span>{p.emoji}</span><div><b>{p.name}<i>{p.words.length} 词</i></b><small>{p.description}</small></div>{pack===p.id&&<Check/>}</button>)}</div><section className="round-time"><div><b>这一轮玩多久？</b><small>时间到后自动统计猜对题数</small></div><div>{[120,180,240,300].map(seconds=><button key={seconds} className={duration===seconds?"active":""} onClick={()=>setDuration(seconds)}><b>{seconds}</b><small>秒</small></button>)}</div></section><section className="custom-pack"><div><b>导入自己的题库</b><small>每行一个词，也支持逗号分隔；最多 500 个。</small></div><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder={"例如：\n跳绳\n吃火锅\n小猫钓鱼"}/><div><label className="secondary"><Upload/>选择 TXT 文件<input type="file" accept=".txt,.csv,text/plain" onChange={e=>importFile(e.target.files?.[0])}/></label><button className="secondary" disabled={!parseWords(draft).length} onClick={saveCustom}><Plus/>保存为我的题库</button></div></section>{confirmAdult&&<div className="adult-confirm"><span>🔞</span><div><b>确认所有玩家均已成年</b><p>18 禁题库只适合自愿参与的成年人，任何题目都可以跳过。</p></div><button onClick={()=>{setConfirmAdult(false);setTimeout(start,0)}}>确认进入</button></div>}<button className="primary charades-start" disabled={pack==="custom"&&!custom.length} onClick={start}><Sparkles/>开始 {duration} 秒回合</button><p className="rotate-hint">📱 开始后请横拿手机，点击屏幕左右两侧操作</p></div></div>
}
type TDGender="男"|"女"|"其他"|"不公开";
type TDMode="真心话"|"大冒险";
type TDDifficulty="温和"|"欢乐"|"刺激"|"极限";
type TDPlayer={id:string;name:string;gender:TDGender;avatar:string;age:number;partnerId:string;birthday:string};
type TDSettings={mode:"真心话"|"大冒险"|"随机";difficulty:TDDifficulty;age:"全年龄"|"16+"|"18+";alcohol:boolean;couple:boolean;touch:boolean;prank:boolean;autoRandom:boolean};
type TDQuestion={id:string;mode:TDMode;text:string;difficulty:TDDifficulty;age:0|16|18;alcohol?:boolean;couple?:boolean;touch?:boolean;prank?:boolean;target?:boolean};
const TD_AVATARS=["🐱","😸","😻","😼","😺","🙀"];
const TD_QUESTIONS:TDQuestion[]=truthQuestionSeeds as TDQuestion[];
type BoxRarity="普通"|"稀有"|"史诗"|"传说"|"神话";
type BoxItem={id:string;name:string;icon:string;rarity:BoxRarity;description:string;effect:"redraw"|"skip"|"immune"|"shield"|"transfer"|"together"|"double"|"designate"|"extra"|"all"|"empty"};
type BoxProfile={items:BoxItem[];bravery:number;completed:number;history:string[];lastUsed:Record<string,number>};
type BoxStore=Record<string,BoxProfile>;
const EMPTY_PROFILE:BoxProfile={items:[],bravery:0,completed:0,history:[],lastUsed:{}};
const BOX_ITEMS:BoxItem[]=[
  {id:"redraw",name:"换题券",icon:"🔄",rarity:"普通",description:"免费更换当前题目一次",effect:"redraw"},{id:"skip",name:"跳过券",icon:"⏭️",rarity:"普通",description:"直接结束一次挑战",effect:"skip"},{id:"empty",name:"空空如也",icon:"🐾",rarity:"普通",description:"小猫在盒子里留了一个爪印",effect:"empty"},
  {id:"immune",name:"免罚券",icon:"🛡️",rarity:"稀有",description:"免除一次惩罚",effect:"immune"},{id:"shield",name:"护盾",icon:"💠",rarity:"稀有",description:"未来两轮挡住第一次惩罚",effect:"shield"},{id:"transfer",name:"转移卡",icon:"🎯",rarity:"稀有",description:"把当前惩罚转给另一位玩家",effect:"transfer"},{id:"together",name:"共患难",icon:"🤝",rarity:"稀有",description:"指定一人与你共同完成",effect:"together"},
  {id:"double",name:"双倍惩罚",icon:"💥",rarity:"史诗",description:"让本轮惩罚效果加倍",effect:"double"},{id:"designate",name:"指定幸运儿",icon:"👑",rarity:"史诗",description:"下一轮直接指定幸运儿",effect:"designate"},{id:"extra",name:"再抽一次",icon:"🎁",rarity:"史诗",description:"立即再开启一个盲盒",effect:"extra"},
  {id:"all",name:"全员盲盒",icon:"🎊",rarity:"传说",description:"所有玩家各获得一次盲盒",effect:"all"},{id:"legend-shield",name:"三回合护盾",icon:"🏰",rarity:"传说",description:"未来三轮第一次惩罚无效",effect:"shield"},
  {id:"cat-god",name:"猫神降临",icon:"🌈",rarity:"神话",description:"全员立即开启一个盲盒",effect:"all"},{id:"fate-king",name:"命运之主",icon:"👑",rarity:"神话",description:"未来三轮由你指定幸运儿",effect:"designate"}
];
const rarityRank:Record<BoxRarity,number>={普通:0,稀有:1,史诗:2,传说:3,神话:4};
const rarityImage:Record<BoxRarity,string>={普通:"common",稀有:"rare",史诗:"epic",传说:"legendary",神话:"mythic"};
function rollBox(min:BoxRarity="普通"){const n=Math.random()*100;let rarity:BoxRarity=n<45?"普通":n<75?"稀有":n<90?"史诗":n<98?"传说":"神话";if(rarityRank[rarity]<rarityRank[min])rarity=min;if(rarity==="普通"&&Math.random()<.45)return BOX_ITEMS.find(x=>x.effect==="empty")!;const pool=BOX_ITEMS.filter(x=>x.rarity===rarity&&x.effect!=="empty");return pool[Math.floor(Math.random()*pool.length)]}
function BoxCat({name,className=""}:{name:string;className?:string}){const base=process.env.NEXT_PUBLIC_BASE_PATH||"";return <img className={`box-cat ${className}`} src={`${base}/icons/boxes/${name}.png`} alt="小猫盲盒图标"/>}

function TruthOrDare({players,onClose}:{players:string[];onClose:()=>void}){
  const seed=players.map((name,i)=>({id:`p-${i}-${name}`,name,gender:"不公开" as TDGender,avatar:TD_AVATARS[i%TD_AVATARS.length],age:18,partnerId:"",birthday:""}));
  const[roster,setRoster]=useStored<TDPlayer[]>("truth_players",seed.length?seed:[{id:"p-1",name:"玩家 1",gender:"不公开",avatar:"🐱",age:18,partnerId:"",birthday:""},{id:"p-2",name:"玩家 2",gender:"不公开",avatar:"😸",age:18,partnerId:"",birthday:""}]);
  const[settings,setSettings]=useStored<TDSettings>("truth_settings",{mode:"随机",difficulty:"欢乐",age:"全年龄",alcohol:false,couple:false,touch:false,prank:false,autoRandom:false});
  const[boxes,setBoxes]=useStored<BoxStore>("cat_mystery_boxes",{});
  const[stage,setStage]=useState<"players"|"settings"|"wheel"|"choose"|"question"|"box"|"result"|"penalty"|"drink">("players"),[chosen,setChosen]=useState<TDPlayer|null>(null),[spinning,setSpinning]=useState(false),[current,setCurrent]=useState<TDQuestion|null>(null),[target,setTarget]=useState<TDPlayer|null>(null),[rounds,setRounds]=useState(0),[used,setUsed]=useState<string[]>([]),[penalty,setPenalty]=useState(""),[favorites,setFavorites]=useStored<string[]>("truth_favorites",[]),[shield,setShield]=useState(0),[confirmExit,setConfirmExit]=useState(false),[boxItem,setBoxItem]=useState<BoxItem|null>(null),[boxOpened,setBoxOpened]=useState(false),[pendingBoxes,setPendingBoxes]=useState(0),[drinkResult,setDrinkResult]=useState(""),[useConfirm,setUseConfirm]=useState<BoxItem|null>(null),[activeUsed,setActiveUsed]=useState(false),[transferTarget,setTransferTarget]=useState<TDPlayer|null>(null),[defenseAsked,setDefenseAsked]=useState(false),[blockedTargets,setBlockedTargets]=useState<string[]>([]),[itemNotice,setItemNotice]=useState(""),[discardChoice,setDiscardChoice]=useState<number|"new"|null>(null),[targetPicker,setTargetPicker]=useState<"transfer"|"together"|"designate"|null>(null),[designatedNext,setDesignatedNext]=useState<TDPlayer|null>(null);
  const updatePlayer=(id:string,patch:Partial<TDPlayer>)=>setRoster(list=>list.map(p=>p.id===id?{...p,...patch}:p));
  useEffect(()=>{if(String(settings.difficulty)==="自定义")setSettings(s=>({...s,difficulty:"欢乐"}))},[settings.difficulty,setSettings]);
  const setPartner=(id:string,partnerId:string)=>setRoster(list=>{const player=list.find(p=>p.id===id),partner=list.find(p=>p.id===partnerId);return list.map(p=>{if(p.id===id)return{...p,partnerId};if(partnerId&&p.id===partnerId)return{...p,partnerId:id};if(p.id===player?.partnerId||p.id===partner?.partnerId||p.partnerId===id||p.partnerId===partnerId)return{...p,partnerId:""};return p})});
  const addPlayer=()=>setRoster(list=>[...list,{id:`p-${Date.now()}`,name:`玩家 ${list.length+1}`,gender:"不公开",avatar:TD_AVATARS[list.length%TD_AVATARS.length],age:18,partnerId:"",birthday:""}]);
  const diffRank:Record<TDDifficulty,number>={温和:1,欢乐:2,刺激:3,极限:4};
  const selectedDifficulty=diffRank[settings.difficulty]||2;
  const maxAge=settings.age==="全年龄"?0:settings.age==="16+"?16:18;
  const drawQuestion=(request:"真心话"|"大冒险"|"随机",person=chosen)=>{
    const mode:TDMode=request==="随机"?(settings.mode==="随机"?(Math.random()<.5?"真心话":"大冒险"):settings.mode):request;
    let pool=TD_QUESTIONS.filter(q=>q.mode===mode&&diffRank[q.difficulty]===selectedDifficulty&&q.age<=maxAge&&(!q.alcohol||settings.alcohol)&&(!q.couple||settings.couple)&&(!q.touch||settings.touch)&&(!q.prank||settings.prank)&&!used.includes(q.id));
    if(!pool.length){setUsed([]);pool=TD_QUESTIONS.filter(q=>q.mode===mode&&diffRank[q.difficulty]===selectedDifficulty&&q.age<=maxAge&&(!q.alcohol||settings.alcohol)&&(!q.couple||settings.couple)&&(!q.touch||settings.touch)&&(!q.prank||settings.prank))}
    if(!pool.length){setTarget(null);setCurrent({id:`empty-${Date.now()}`,mode,text:"当前难度、年龄与内容开关组合下没有可用题目，请返回设置调整年龄或开启对应附加题库。",difficulty:settings.difficulty,age:0});setStage("question");return}
    const picked=pool[Math.floor(Math.random()*pool.length)];let other=roster.filter(p=>p.id!==person?.id);const assigned=picked.couple&&person?.partnerId?(roster.find(p=>p.id===person.partnerId)||null):(other[Math.floor(Math.random()*other.length)]||null);
    setTarget(assigned);setCurrent(picked);setUsed(ids=>[...ids,picked.id]);setStage("question")
  };
  const spin=()=>{if(spinning||!roster.length)return;setSpinning(true);window.setTimeout(()=>{const person=designatedNext||roster[Math.floor(Math.random()*roster.length)];setDesignatedNext(null);setChosen(person);setSpinning(false);if(settings.autoRandom)drawQuestion("随机",person);else setStage("choose")},1100)};
  const profile=(name=chosen?.name||"")=>boxes[name]||EMPTY_PROFILE;
  const openEarnedBox=()=>{if(!chosen)return;const nextBravery=profile().bravery+1,min:BoxRarity=nextBravery>=10?"史诗":nextBravery>=5?"稀有":"普通";setBoxItem(rollBox(min));setBoxOpened(false);setDiscardChoice(null);setPendingBoxes(0);setStage("box")};
  const complete=()=>{if(!chosen)return;const next=rounds+1;setRounds(next);setBoxes(all=>{const p=all[chosen.name]||EMPTY_PROFILE;return{...all,[chosen.name]:{...p,bravery:p.bravery+1,completed:p.completed+1,history:[`完成第 ${next} 轮`,...p.history].slice(0,20)}}});openEarnedBox()};
  const resetBravery=()=>{if(chosen)setBoxes(all=>{const p=all[chosen.name]||EMPTY_PROFILE;return{...all,[chosen.name]:{...p,bravery:0,history:["放弃挑战，勇气值清零",...p.history].slice(0,20)}}})};
  const giveUp=()=>{resetBravery();if(shield>0){setShield(v=>v-1);setPenalty("护盾生效，本轮安全跳过 ✨");setStage("penalty");return}if(settings.alcohol){setDrinkResult("");setStage("drink")}else{const pool=["做 10 个深蹲","唱两句歌","模仿一种动物 20 秒","原地转三圈"];setPenalty(pool[Math.floor(Math.random()*pool.length)]);setStage("penalty")}};
  const spinDrink=()=>{const options=[["一口",20],["两口",35],["三口",10],["半杯",15],["一杯",15],["两杯",5]] as const,n=Math.random()*100;let total=0,result="一口";for(const[o,w]of options){total+=w;if(n<total){result=o;break}}setDrinkResult(result)};
  const finishBoxChoice=()=>{setDiscardChoice(null);if(pendingBoxes>0){setPendingBoxes(v=>v-1);setBoxItem(rollBox("稀有"));setBoxOpened(false)}else setStage("result")};
  const saveBox=()=>{if(!chosen||!boxItem)return;setBoxes(all=>{const p=all[chosen.name]||EMPTY_PROFILE;if(boxItem.effect==="empty")return{...all,[chosen.name]:{...p,history:[`开启${boxItem.rarity}盲盒：空盒`,...p.history].slice(0,20)}};if(p.items.length>=3)return all;return{...all,[chosen.name]:{...p,items:[...p.items,boxItem],history:[`获得${boxItem.rarity}道具：${boxItem.name}`,...p.history].slice(0,20)}}});finishBoxChoice()};
  const discardBox=()=>finishBoxChoice();
  const confirmFullBagChoice=()=>{if(!chosen||!boxItem||discardChoice===null)return;if(discardChoice==="new"){setBoxes(all=>{const p=all[chosen.name]||EMPTY_PROFILE;return{...all,[chosen.name]:{...p,history:[`放弃新道具：${boxItem.name}`,...p.history].slice(0,20)}}})}else{const index=discardChoice;setBoxes(all=>{const p=all[chosen.name]||EMPTY_PROFILE,removed=p.items[index],items=p.items.map((item,i)=>i===index?boxItem:item);return{...all,[chosen.name]:{...p,items,history:[`丢弃${removed?.name||"旧道具"}，换入${boxItem.name}`,...p.history].slice(0,20)}}})}finishBoxChoice()};
  const useItem=(item:BoxItem)=>{if(!chosen||activeUsed)return;const p=profile();if(rounds-(p.lastUsed[item.id]??-99)<2)return;setBoxes(all=>{const old=all[chosen.name]||EMPTY_PROFILE;return{...all,[chosen.name]:{...old,items:old.items.filter((x,i)=>!(x.id===item.id&&i===old.items.findIndex(y=>y.id===item.id))),lastUsed:{...old.lastUsed,[item.id]:rounds},history:[`使用：${item.name}`,...old.history].slice(0,20)}}});setActiveUsed(true);setUseConfirm(null);if(item.effect==="immune"||item.effect==="shield"){if(item.effect==="immune")resetBravery();setShield(v=>v+(item.id==="legend-shield"?3:1));setItemNotice(`${item.name}已生效：下一次惩罚将被挡住`)}if(item.effect==="redraw"&&current){drawQuestion(current.mode);setItemNotice("换题券已使用，猫猫重新抽了一题")}if(item.effect==="skip"){resetBravery();nextRound()}if(item.effect==="together")setTargetPicker("together");if(item.effect==="double")setItemNotice("双倍效果已生效：本题次数或时长加倍");if(item.effect==="extra"){setBoxItem(rollBox());setBoxOpened(false);setStage("box")}if(item.effect==="transfer"){setBlockedTargets([]);setDefenseAsked(false);setTargetPicker("transfer")}if(item.effect==="designate")setTargetPicker("designate")};
  const applyItemTarget=(player:TDPlayer)=>{if(targetPicker==="together"){setTarget(player);setItemNotice(`共患难已生效：${player.name} 将与你一起完成本题`)}else if(targetPicker==="transfer"){setTransferTarget(player);setItemNotice(`转移卡已生效：惩罚转移给 ${player.name}`)}else if(targetPicker==="designate"){setDesignatedNext(player);setItemNotice(`指定成功：下一轮幸运儿是 ${player.name}`)}setTargetPicker(null)};
  const targetDefense=transferTarget?(boxes[transferTarget.name]?.items.find(x=>x.effect==="shield"||x.effect==="immune")||null):null;
  const useTargetDefense=()=>{if(!transferTarget||!targetDefense||!chosen)return;const blocked=[...blockedTargets,transferTarget.id];setBoxes(all=>{const old=all[transferTarget.name]||EMPTY_PROFILE;return{...all,[transferTarget.name]:{...old,items:old.items.filter((x,i)=>!(x.id===targetDefense.id&&i===old.items.findIndex(y=>y.id===targetDefense.id))),history:[`使用${targetDefense.name}挡住了转移惩罚`,...old.history].slice(0,20)}}});const next=roster.find(p=>p.id!==chosen.id&&!blocked.includes(p.id));setBlockedTargets(blocked);setDefenseAsked(false);if(next)setTransferTarget(next);else{setTransferTarget(null);setPenalty("所有候选人都使用了护盾，惩罚取消 ✨")}};
  const nextRound=()=>{setChosen(null);setCurrent(null);setTarget(null);setPenalty("");setItemNotice("");setActiveUsed(false);setTransferTarget(null);setTargetPicker(null);setBlockedTargets([]);setDefenseAsked(false);setStage("wheel")};
  const usableItems=(phase:"choose"|"question"|"penalty")=>{const allowed:Record<typeof phase,BoxItem["effect"][]>={choose:["immune","shield","designate"],question:["redraw","skip","immune","shield","together","double","designate"],penalty:["immune","shield","transfer"]},items=profile().items.filter(item=>allowed[phase].includes(item.effect));if(!items.length)return null;return <section className="usable-items"><div className="usable-items-title"><span>🎒</span><div><b>{chosen?.name} 的可用道具</b><small>{activeUsed?"本轮已经使用过道具":"每轮最多使用 1 张 · 同类道具使用后冷却 2 轮"}</small></div><em>{profile().items.length}/3</em></div><div className="inventory-cards">{items.map((item,i)=>{const elapsed=rounds-(profile().lastUsed[item.id]??-99),cooling=elapsed<2,remaining=Math.max(1,2-elapsed);return <button key={`${item.id}-${i}`} disabled={activeUsed||cooling} onClick={()=>setUseConfirm(item)}><span>{item.icon}</span><b>{item.name}</b><small>{item.description}</small>{cooling&&<em>⏳ 冷却中，还需等待 {remaining} 轮</em>}</button>})}</div></section>};
  const share=async()=>{if(!current)return;const text=`${current.mode}｜${chosen?.name}\n${current.text.replace("{target}",target?.name||"一位玩家")}`;try{if(navigator.share)await navigator.share({title:"猫咪派对",text});else await navigator.clipboard.writeText(text)}catch{}};
  return <div className="fullscreen td-screen"><Head onClose={()=>setConfirmExit(true)} title="🎲 真心话大冒险"/><div className="td-shell">
    {stage==="players"&&<><TDHost icon="👋" title="先认识今晚的玩家" text="资料只保存在这台设备上，年龄和性别可以不公开。"/><div className="td-player-list">{roster.map(p=><section className="td-player" key={p.id}><button className="td-avatar" onClick={()=>updatePlayer(p.id,{avatar:TD_AVATARS[(TD_AVATARS.indexOf(p.avatar)+1)%TD_AVATARS.length]})}>{p.avatar}</button><div><input value={p.name} onChange={e=>updatePlayer(p.id,{name:e.target.value})} aria-label="玩家昵称"/><div className="td-inline"><select value={p.gender} onChange={e=>updatePlayer(p.id,{gender:e.target.value as TDGender})}><option>男</option><option>女</option><option>其他</option><option>不公开</option></select><label>年龄 <input type="number" min="0" max="120" value={p.age||""} onChange={e=>updatePlayer(p.id,{age:Number(e.target.value)})}/></label><label>生日 <input type="date" value={p.birthday} onChange={e=>updatePlayer(p.id,{birthday:e.target.value})}/></label><label className="td-partner">❤️ 与谁是情侣 <select value={p.partnerId||""} onChange={e=>setPartner(p.id,e.target.value)}><option value="">无</option>{roster.filter(x=>x.id!==p.id).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div></div><button className="td-delete" disabled={roster.length<=2} onClick={()=>setRoster(list=>list.filter(x=>x.id!==p.id).map(x=>x.partnerId===p.id?{...x,partnerId:""}:x))}><X/></button></section>)}</div><div className="td-row"><button className="secondary" onClick={addPlayer}><Plus/>添加玩家</button><button className="secondary" onClick={()=>setRoster(list=>[...list].sort(()=>Math.random()-.5))}><Shuffle/>随机排序</button></div><button className="primary td-main" disabled={roster.length<2||roster.some(p=>!p.name.trim())} onClick={()=>setStage("settings")}>下一步：游戏设置</button></>}
    {stage==="settings"&&<><TDHost icon="⚙️" title="今晚玩到什么程度？" text="难度严格匹配；年龄向下兼容，其他开关会追加对应内容。"/><TDChoice title="🎭 游戏模式" values={["真心话","大冒险","随机"]} value={settings.mode} set={value=>setSettings(s=>({...s,mode:value as TDSettings["mode"]}))}/><TDChoice title="🎚 难度" values={["温和","欢乐","刺激","极限"]} value={settings.difficulty} set={value=>setSettings(s=>({...s,difficulty:value as TDDifficulty}))}/><TDChoice title="🔞 年龄限制" values={["全年龄","16+","18+"]} value={settings.age} set={value=>setSettings(s=>({...s,age:value as TDSettings["age"]}))}/><div className="td-toggles"><TDToggle label="🍺 是否喝酒" checked={settings.alcohol} set={v=>setSettings(s=>({...s,alcohol:v}))}/><TDToggle label="❤️ 开启情侣内容" checked={settings.couple} set={v=>setSettings(s=>({...s,couple:v}))}/><TDToggle label="🤝 允许身体接触" checked={settings.touch} set={v=>setSettings(s=>({...s,touch:v}))}/><TDToggle label="😂 允许整蛊互动" checked={settings.prank} set={v=>setSettings(s=>({...s,prank:v}))}/><TDToggle label="🎲 抽中后自动随机" checked={settings.autoRandom} set={v=>setSettings(s=>({...s,autoRandom:v}))}/></div><p className="td-consent">选择难度后只会抽取该难度题目。16+ 包含全年龄年龄标签，18+ 包含全年龄与 16+ 年龄标签；附加开关只追加当前难度对应题库。任何身体接触都必须再次征得双方同意。</p><div className="td-row"><button className="secondary" onClick={()=>setStage("players")}>返回玩家</button><button className="primary" onClick={()=>setStage("wheel")}>开始游戏</button></div></>}
    {stage==="wheel"&&<><TDHost icon="🎡" title="转动幸运轮盘" text={`第 ${rounds+1} 轮 · ${settings.difficulty}模式`}/><div className={spinning?"td-wheel spinning":"td-wheel"}>{roster.map((p,i)=><span key={p.id} style={{transform:`rotate(${i*360/roster.length}deg) translateY(-105px) rotate(-${i*360/roster.length}deg)`}}>{p.avatar}</span>)}<b>🐾</b></div><div className="box-status-row">{roster.map(p=><div key={p.id}><b>{p.avatar} {p.name}</b><small>勇气 {profile(p.name).bravery} · 道具 {profile(p.name).items.length}/3</small></div>)}</div><button className="primary td-main" disabled={spinning} onClick={spin}>{spinning?"猫猫正在选…":"开始抽人"}</button></>}
    {stage==="choose"&&chosen&&<><TDHost icon="🎉" title={`幸运儿：${chosen.name}`} text="可以先使用下方道具，再选择真心话或大冒险。"/><div className="td-lucky"><span>{chosen.avatar}</span><b>{chosen.name}</b><small>{chosen.gender} · {chosen.age?`${chosen.age} 岁`:"年龄保密"}</small></div>{usableItems("choose")}{itemNotice&&<p className="item-notice">✨ {itemNotice}</p>}<div className="td-mode-cards"><button disabled={settings.mode==="大冒险"} onClick={()=>drawQuestion("真心话")}><span>❤️</span><b>真心话</b></button><button disabled={settings.mode==="真心话"} onClick={()=>drawQuestion("大冒险")}><span>🔥</span><b>大冒险</b></button><button onClick={()=>drawQuestion("随机")}><span>🎲</span><b>随机</b></button></div></>}
    {stage==="question"&&current&&chosen&&<><TDHost icon="📜" title="猫猫出题啦" text={`${current.difficulty} · ${settings.age}`}/><article className={current.mode==="真心话"?"td-question truth":"td-question dare"}><div><span>{current.mode==="真心话"?"❤️":"🔥"}</span><b>{current.mode}</b><small>{chosen.avatar} {chosen.name}</small></div><h1>{current.text.replace("{target}",target?.name||"一位玩家")}</h1>{target&&(current.target||itemNotice.includes("共患难"))&&<p>共同玩家：<strong>{target.avatar} {target.name}</strong></p>}<footer>不舒服可以直接放弃，开心最重要</footer></article>{itemNotice&&<p className="item-notice">✨ {itemNotice}</p>}{usableItems("question")}<div className="td-actions"><button className={favorites.includes(current.id)?"secondary saved":"secondary"} onClick={()=>setFavorites(list=>list.includes(current.id)?list.filter(id=>id!==current.id):[...list,current.id])}><Bookmark/>收藏</button><button className="secondary" onClick={()=>drawQuestion(current.mode)}><Shuffle/>换题</button><button className="secondary" onClick={share}>分享</button></div><div className="td-row"><button className="td-giveup" onClick={giveUp}>放弃</button><button className="primary" onClick={complete}><Check/>已完成</button></div></>}
    {stage==="box"&&boxItem&&chosen&&<><TDHost icon="🎁" title="小猫送来了神秘礼物" text={`连续完成 ${profile().bravery} 轮 · 点击礼盒揭晓`}/><div className={`mystery-box ${boxOpened?"opened":""}`}>{boxOpened?<><BoxCat name={rarityImage[boxItem.rarity]}/><span>{boxItem.rarity}</span><h1>{boxItem.icon} {boxItem.name}</h1><p>{boxItem.description}</p>{profile().items.length>=3&&boxItem.effect!=="empty"?<div className="bag-replace"><h2>背包已满，请选择丢弃一张</h2><small>现有 3 张道具和新道具共 4 张，点选其中一张抛弃。</small><div className="bag-four-cards">{profile().items.map((item,i)=><button key={`${item.id}-${i}`} className={discardChoice===i?"selected":""} onClick={()=>setDiscardChoice(i)}><span>{item.icon}</span><b>{item.name}</b><small>{item.rarity} · 背包内</small>{discardChoice===i&&<em>准备丢弃</em>}</button>)}<button className={discardChoice==="new"?"selected new-item":"new-item"} onClick={()=>setDiscardChoice("new")}><span>{boxItem.icon}</span><b>{boxItem.name}</b><small>{boxItem.rarity} · 新抽中</small>{discardChoice==="new"&&<em>准备丢弃</em>}</button></div><button className="primary confirm-replace" disabled={discardChoice===null} onClick={confirmFullBagChoice}>{discardChoice==="new"?"放弃新道具":"丢弃旧道具并换入新道具"}</button></div>:<><button className="primary" onClick={saveBox}>{boxItem.effect==="empty"?"收下猫爪印":"放入状态卡"}</button><button className="secondary" onClick={discardBox}>放弃这个道具</button></>}</>:<button onClick={()=>setBoxOpened(true)}><BoxCat name="open"/><b>点击开启</b></button>}</div></>}
    {stage==="result"&&<><TDHost icon="🎊" title="挑战完成！" text="盲盒已结算，下一轮继续升温。"/><div className="td-result"><BoxCat name="confetti"/><h1>✅ 已完成</h1><p>{chosen?.name} 完成了第 {rounds} 轮 · 勇气值 {profile().bravery}</p></div><button className="primary td-main" onClick={nextRound}>重新抽人</button></>}
    {stage==="drink"&&<><TDHost icon="🍹" title="自愿饮品转盘" text="只在所有人自愿且达到当地法定年龄时使用。"/><div className={drinkResult?"drink-wheel landed":"drink-wheel"}><BoxCat name="wheel"/><h1>{drinkResult||"准备转动"}</h1><p>概率：两口最高；两杯仅 5%</p></div><p className="td-consent">杯量请在开始前共同约定。结果可随时换成无酒精饮品、10 个深蹲或唱两句歌，不劝酒、不灌酒。</p><div className="td-row"><button className="secondary" onClick={()=>{setPenalty("做 10 个深蹲或唱两句歌");setStage("penalty")}}>改为无酒精挑战</button><button className="primary" onClick={drinkResult?nextRound:spinDrink}>{drinkResult?"下一轮":"转动转盘"}</button></div></>}
    {stage==="penalty"&&<><TDHost icon="😼" title="放弃惩罚" text="可使用状态卡，也可以换成更轻松的项目。"/><div className="td-penalty"><BoxCat name="penalty"/><h1>{transferTarget?`${penalty} → ${transferTarget.name}`:penalty}</h1></div>{itemNotice&&<p className="item-notice">✨ {itemNotice}</p>}{chosen&&usableItems("penalty")}<div className="td-row"><button className="secondary" onClick={()=>{const pool=["做 10 个深蹲","唱两句歌","模仿一种动物 20 秒","原地转三圈"];setPenalty(pool[Math.floor(Math.random()*pool.length)])}}><Shuffle/>换一个</button><button className="primary" onClick={nextRound}>接受结果，下一轮</button></div></>}
  </div>{targetPicker&&chosen&&<div className="exit-confirm"><div className="exit-confirm-card target-picker"><BoxCat name="draw"/><h2>{targetPicker==="transfer"?"把惩罚转移给谁？":targetPicker==="together"?"选择谁和你一起？":"指定下一轮幸运儿"}</h2><p>可以手动选择，也可以交给小猫随机抽取。</p><div className="target-player-grid">{roster.filter(p=>p.id!==chosen.id).map(p=><button key={p.id} onClick={()=>applyItemTarget(p)}><span>{p.avatar}</span><b>{p.name}</b></button>)}</div><button className="primary random-target" onClick={()=>{const candidates=roster.filter(p=>p.id!==chosen.id);if(candidates.length)applyItemTarget(candidates[Math.floor(Math.random()*candidates.length)])}}><Shuffle/>小猫随机选一个</button></div></div>}{transferTarget&&targetDefense&&!defenseAsked&&<div className="exit-confirm"><div className="exit-confirm-card"><BoxCat name="reveal"/><h2>{transferTarget.name} 要使用“{targetDefense.name}”吗？</h2><p>使用后这张状态卡会消失，转移惩罚将继续寻找下一位没有拦截的玩家。</p><div><button className="secondary" onClick={()=>setDefenseAsked(true)}>不使用，接受惩罚</button><button className="primary" onClick={useTargetDefense}>确认使用</button></div></div></div>}{useConfirm&&<div className="exit-confirm"><div className="exit-confirm-card"><BoxCat name="reveal"/><h2>使用“{useConfirm.name}”？</h2><p>{useConfirm.description}。使用后会从状态卡中消失，本轮不能再使用其他主动道具。</p><div><button className="secondary" onClick={()=>setUseConfirm(null)}>取消</button><button className="primary" onClick={()=>useItem(useConfirm)}>确认使用</button></div></div></div>}{confirmExit&&<div className="exit-confirm" role="dialog" aria-modal="true" aria-labelledby="truth-exit-title"><div className="exit-confirm-card"><span className="exit-cat">ฅ^•ﻌ•^ฅ</span><h2 id="truth-exit-title">要退出真心话大冒险吗？</h2><p>当前回合进度会结束，玩家资料、盲盒状态和游戏设置仍会保存在本机。</p><div><button className="secondary" onClick={()=>setConfirmExit(false)}>继续游戏</button><button className="exit-danger" onClick={onClose}>确认退出</button></div></div></div>}</div>
}
function TDHost({icon,title,text}:{icon:string;title:string;text:string}){return <header className="td-host-card"><Cat mood="wink"/><span>{icon}</span><div><h1>{title}</h1><p>{text}</p></div></header>}
function TDChoice({title,values,value,set}:{title:string;values:string[];value:string;set:(v:string)=>void}){return <section className="td-setting"><b>{title}</b><div>{values.map(v=><button key={v} className={value===v?"on":""} onClick={()=>set(v)}>{v}</button>)}</div></section>}
function TDToggle({label,checked,set}:{label:string;checked:boolean;set:(v:boolean)=>void}){return <label className="td-toggle"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)}/><i/></label>}
function Prompt({game,players,level,onClose}:{game:Game;players:string[];level:Level;onClose:()=>void}){const pool=prompts[game.id]||prompts.randomchallenge;const[used,setUsed]=useState<number[]>([]),[idx,setIdx]=useState<number|null>(null),[person,setPerson]=useState("");const draw=()=>{let left=pool.map((_,i)=>i).filter(i=>!used.includes(i));if(!left.length){setUsed([]);left=pool.map((_,i)=>i)}const n=left[Math.floor(Math.random()*left.length)];setIdx(n);setUsed(x=>[...x,n]);if(players.length)setPerson(players[Math.floor(Math.random()*players.length)])};return <div className="fullscreen play-screen"><Head onClose={onClose} title={`${game.emoji} ${game.name}`}/><div className="play-content">{idx===null?<><Cat mood="party"/><h1>准备好了吗？</h1><p>{pool.length} 张题卡 · {level}模式</p><button className="primary big" onClick={draw}><Sparkles/>抽一张</button></>:<><span className="turn-label">{person&&`${person} 的题目`}</span><div className="prompt-card"><small>第 {used.length} 题</small><h1>{pool[idx]}</h1><span>不舒服可以跳过，开心最重要</span></div><div className="play-buttons"><button className="secondary" onClick={draw}><Shuffle/>跳过</button><button className="primary" onClick={draw}><Check/>完成，下一题</button></div></>}</div></div>}
function Identity({game,players,onClose}:{game:Game;players:string[];onClose:()=>void}){const[roles,setRoles]=useState<string[]>([]),[index,setIndex]=useState(0),[show,setShow]=useState(false),[done,setDone]=useState(false);const begin=()=>{let r:string[]=[];if(game.id==="undercover"){const pair=[["牛奶","豆浆"],["橙子","橘子"],["饺子","馄饨"]][Math.floor(Math.random()*3)];r=players.map(()=>pair[0]);r[Math.floor(Math.random()*players.length)]=pair[1]}else if(game.id==="dontdo"){r=["不能说我","不能摸头发","不能回答是","不能叫别人名字","不能看时间","不能翘腿"].slice(0,players.length).sort(()=>Math.random()-.5)}else{const w=players.length>=9?3:2;r=[...Array(w).fill("狼人"),"预言家","女巫",...Array(Math.max(0,players.length-w-2)).fill("村民")].sort(()=>Math.random()-.5)}setRoles(r)};if(!roles.length)return <div className="fullscreen identity-screen"><Head onClose={onClose} title={`${game.emoji} 身份准备`}/><div className="identity-intro"><Cat mood="wink"/><h1>秘密传阅喵</h1><p>每个人只看自己的身份，看完藏好再交给下一位。</p><div className="player-preview">{players.map((p,i)=><span key={p}><i>{i+1}</i>{p}</span>)}</div>{players.length>=game.min?<button className="primary big" onClick={begin}>开始分配身份</button>:<div className="warning">至少需要 {game.min} 位玩家。</div>}</div></div>;if(done)return <div className="fullscreen identity-screen"><Head onClose={onClose} title={game.name}/><div className="identity-intro"><Cat mood="party"/><h1>身份分配完成</h1><p>把手机交给主持人，游戏开始喵！</p><button className="primary big" onClick={onClose}>进入讨论</button></div></div>;const next=()=>{setShow(false);if(index===players.length-1)setDone(true);else setIndex(i=>i+1)};return <div className="fullscreen identity-screen"><Head onClose={onClose} title={`${index+1} / ${players.length}`}/><div className="identity-pass"><span className="turn-label">请把手机交给</span><h1>{players[index]}</h1>{show?<><div className="role-card"><small>你的身份 / 词语是</small><h2>{roles[index]}</h2><p>记住秘密，不要让别人看见</p></div><button className="primary big" onClick={next}>记住了，藏好并传递</button></>:<><div className="hidden-card"><Cat mood="sleep"/><b>秘密藏好啦</b><small>确认周围没有偷看的猫</small></div><button className="primary big" onClick={()=>setShow(true)}>查看我的身份</button></>}</div></div>}
function Head({onClose,title}:{onClose:()=>void;title:string}){return <div className="play-head"><button onClick={onClose}><X/></button><span>{title}</span></div>}

function Tool({type,players,level,onClose}:{type:string;players:string[];level:Level;onClose:()=>void}){if(type==="blindbox")return <BlindBoxCenter players={players} onClose={onClose}/>;if(type==="timer")return <TimerTool title="猫咪计时器" onClose={onClose}/>;if(type==="teams")return <Teams players={players} onClose={onClose}/>;return <Draw type={type} players={players} level={level} onClose={onClose}/>}
function BlindBoxCenter({players,onClose}:{players:string[];onClose:()=>void}){const[boxes]=useStored<BoxStore>("cat_mystery_boxes",{}),[selected,setSelected]=useState(players[0]||Object.keys(boxes)[0]||"");const names=Array.from(new Set([...players,...Object.keys(boxes)])),p=boxes[selected]||EMPTY_PROFILE;return <div className="fullscreen draw-screen"><Head onClose={onClose} title="🐱 小猫盲盒"/><div className="draw-content blindbox-center"><TDHost icon="🎁" title="全站状态卡" text="所有游戏获得的盲盒道具都会保存在这里。"/><div className="box-player-tabs">{names.map(n=><button className={selected===n?"on":""} key={n} onClick={()=>setSelected(n)}>{n}</button>)}</div>{selected?<><div className="box-profile"><BoxCat name="inventory"/><div><h2>{selected}</h2><p>勇气值 {p.bravery} · 完成 {p.completed} 轮 · 状态卡 {p.items.length}/3</p></div></div><div className="inventory-cards">{p.items.length?p.items.map((item,i)=><div key={`${item.id}-${i}`}><span>{item.icon}</span><b>{item.name}</b><small>{item.rarity} · {item.description}</small><em>进入支持的游戏后确认使用</em></div>):<p className="empty-backpack">还没有道具，完成一轮游戏就有机会获得。</p>}</div>{p.history.length>0&&<div className="history-list"><b>最近记录</b>{p.history.map((x,i)=><span key={`${x}-${i}`}>{x}</span>)}</div>}</>:<div className="empty"><BoxCat name="open"/><h3>先在“我的”中添加玩家</h3></div>}<section className="box-rarity-guide">{(["普通","稀有","史诗","传说","神话"] as BoxRarity[]).map((r,i)=><div key={r}><BoxCat name={rarityImage[r]}/><b>{r}</b><small>{[45,30,15,8,2][i]}%</small></div>)}</section></div></div>}
function TimerTool({title,onClose}:{title:string;onClose:()=>void}){const[sec,setSec]=useState(60),[left,setLeft]=useState(60),[run,setRun]=useState(false);useEffect(()=>{if(!run)return;const id=setInterval(()=>setLeft(x=>x<=1?(setRun(false),0):x-1),1000);return()=>clearInterval(id)},[run]);return <div className="fullscreen timer-screen"><Head onClose={onClose} title={`⏱️ ${title}`}/><div className="timer-content"><Cat mood={left===0?"party":"happy"}/><div className={`timer-ring ${run?"ticking":""}`}><small>{left?"剩余时间":"时间到喵！"}</small><b>{Math.floor(left/60).toString().padStart(2,"0")}:{(left%60).toString().padStart(2,"0")}</b></div><div className="preset-row">{[30,60,90,120].map(s=><button key={s} className={sec===s?"on":""} onClick={()=>{setSec(s);setLeft(s);setRun(false)}}>{s<60?`${s}秒`:`${s/60}分钟`}</button>)}</div><button className="primary big" onClick={()=>left?setRun(x=>!x):(setLeft(sec),setRun(true))}>{run?"暂停":"开始计时"}</button></div></div>}
function Draw({type,players,level,onClose}:{type:string;players:string[];level:Level;onClose:()=>void}){const[kind,setKind]=useState<"玩家"|"奖励"|"惩罚">(type==="pick"||type==="eliminate"?"玩家":type==="cards"?"惩罚":"玩家"),[result,setResult]=useState(""),[history,setHistory]=useState<string[]>([]),[out,setOut]=useState<string[]>([]);const[custom,setCustom]=useStored<string[]>("party_custom_draw",[]),[input,setInput]=useState("");const source=kind==="玩家"?players:kind==="奖励"?[...rewards,...custom]:[...punishments[level],...custom];const available=type==="eliminate"?source.filter(x=>!out.includes(x)):source;const draw=()=>{if(!available.length)return;const r=available[Math.floor(Math.random()*available.length)];setResult(r);setHistory(h=>[r,...h]);if(type==="eliminate")setOut(o=>[...o,r])};const name:{[k:string]:string}={wheel:"幸运转盘",pick:"随机点名",lots:"抽签盒",cards:"奖惩卡片",eliminate:"淘汰抽取"};return <div className="fullscreen draw-screen"><Head onClose={onClose} title={`🐾 ${name[type]}`}/><div className="draw-content"><div className="segmented">{(["玩家","奖励","惩罚"]as const).map(k=><button key={k} className={kind===k?"on":""} onClick={()=>{setKind(k);setResult("")}}>{k}</button>)}</div>{result?<div className="draw-result cat-result"><Cat mood="party"/><small>{kind==="玩家"?"猫猫选中了":"抽取结果"}</small><h1>{result}</h1></div>:<div className="draw-placeholder"><Cat mood="wink"/><h2>{source.length} 个选项准备好了</h2></div>}<button className="primary big" disabled={!available.length} onClick={draw}><Sparkles/>{result?"再抽一次":"开始抽取"}</button>{result&&kind==="惩罚"&&<button className="secondary big" onClick={()=>setResult("本轮免罚 ✨")}><Heart/>本轮免罚</button>}<div className="custom-add"><input value={input} onChange={e=>setInput(e.target.value)} placeholder="添加自定义奖品或惩罚"/><button onClick={()=>{if(input.trim()){setCustom(c=>[...c,input.trim()]);setInput("")}}}><Plus/></button></div>{history.length>0&&<div className="history-list"><b>本轮记录</b>{history.map((h,i)=><span key={`${h}${i}`}><small>{history.length-i}</small>{h}</span>)}</div>}</div></div>}
function Teams({players,onClose}:{players:string[];onClose:()=>void}){const[count,setCount]=useState(2),[teams,setTeams]=useState<string[][]>([]);const make=()=>{const s=[...players].sort(()=>Math.random()-.5),t=Array.from({length:Math.min(count,players.length)},()=>[]as string[]);s.forEach((p,i)=>t[i%t.length].push(p));setTeams(t)};return <div className="fullscreen draw-screen"><Head onClose={onClose} title="🐾 随机分组"/><div className="draw-content"><Cat mood="happy"/><div className="stepper"><button onClick={()=>setCount(c=>Math.max(2,c-1))}><Minus/></button><div><b>{count}</b><span>组</span></div><button onClick={()=>setCount(c=>Math.min(Math.max(2,players.length),c+1))}><Plus/></button></div>{teams.length>0&&<div className="teams-result">{teams.map((t,i)=><div key={i}><b>第 {i+1} 组</b>{t.map(p=><span key={p}>{p}</span>)}</div>)}</div>}<button className="primary big" disabled={players.length<2} onClick={make}><Shuffle/>{teams.length?"重新分组":"开始分组"}</button></div></div>}
