"use client";
import {useEffect,useState} from "react";
import {ChevronRight,Plus,RotateCcw,Shuffle,Sparkles,Trophy,X} from "lucide-react";
type Stage="players"|"settings"|"reveal"|"describe"|"vote"|"voteResult"|"result";
type Role="平民"|"卧底"|"白板";
type Skill={id:string;icon:string;name:string;timing:string;description:string;kind:"describe"|"vote"|"defense"|"passive"|"order"|"info"|"fate"};
type Player={id:string;name:string;role:Role;word:string;alive:boolean;skill?:Skill;used:boolean;votes:number};
type Reward={id:string;owner:string;rarity:"普通"|"稀有"|"史诗"|"传说";opened:boolean;item?:{id:string;name:string;icon:string;rarity:string;description:string;effect:string;weight:number}};
const PAIRS:Record<string,[string,string][]>= {综合:[["牛奶","豆浆"],["橙子","橘子"],["雨伞","雨衣"]],电影:[["哈利·波特","指环王"]],校园:[["班主任","辅导员"],["校服","运动服"]],网络热梗:[["显眼包","社牛"]],情侣:[["牵手","拥抱"]],美食:[["饺子","馄饨"],["火锅","麻辣烫"]],动物:[["猫","老虎"],["海豚","鲨鱼"]]};
const SKILLS:Skill[]=[
 {id:"shield",icon:"🛡",name:"护盾",timing:"自己即将淘汰时",description:"抵消本次淘汰，下一轮继续游戏。",kind:"defense"},{id:"double",icon:"🎙",name:"双倍发言",timing:"自己描述时",description:"本轮可以说两句话。",kind:"describe"},{id:"peek",icon:"🔎",name:"偷看",timing:"投票前",description:"查看一人是否为卧底，不显示词语。",kind:"info"},{id:"mute",icon:"🔇",name:"禁言",timing:"投票前",description:"指定一人下一轮只能说三个字。",kind:"info"},{id:"acting",icon:"🎭",name:"演技",timing:"自己描述时",description:"本轮允许做动作。",kind:"describe"},{id:"captain",icon:"👑",name:"队长",timing:"自己投票时",description:"本轮投票权重 ×2。",kind:"vote"},{id:"abstain",icon:"🚫",name:"弃权",timing:"自己投票时",description:"本轮不参与投票，用于迷惑别人。",kind:"vote"},{id:"shuffle",icon:"🎲",name:"换顺序",timing:"游戏开始前",description:"重新随机描述顺序。",kind:"order"},{id:"first",icon:"🎯",name:"指定首位",timing:"每轮开始前",description:"指定下一轮第一位描述玩家。",kind:"order"},{id:"cat",icon:"🐱",name:"猫咪乱入",timing:"任意时机",description:"触发一个持续完整轮次的命运事件。",kind:"fate"},{id:"lucky",icon:"🎁",name:"好运",timing:"游戏结束时",description:"获胜后额外获得一个奖励盲盒。",kind:"passive"},{id:"emperor",icon:"⭐",name:"欧皇",timing:"游戏结束时",description:"如果获胜，盲盒品质提升一级。",kind:"passive"},{id:"unlucky",icon:"😈",name:"倒霉蛋",timing:"游戏结束时",description:"如果失败，抽两个随机盲盒。",kind:"passive"},{id:"decoy",icon:"🎭",name:"替身",timing:"自己即将淘汰时",description:"选择另一位玩家代替自己淘汰。",kind:"defense"},{id:"silent",icon:"🙈",name:"沉默保护",timing:"描述开始前",description:"本轮可以安全放弃描述。",kind:"describe"}
];
const EVENTS=[{icon:"🌧",name:"猫咪下雨",text:"每人只能说三个字"},{icon:"🌙",name:"月黑风高",text:"不能描述颜色"},{icon:"🤫",name:"安静模式",text:"每人只能说一句"},{icon:"🪞",name:"镜像世界",text:"描述顺序反过来"},{icon:"🎭",name:"演技模式",text:"必须带表情描述"},{icon:"🎲",name:"极速模式",text:"每人只有 10 秒"},{icon:"🎤",name:"Rap 模式",text:"描述必须押韵"}];
const POSITIVE=[{id:"fish",name:"小鱼干",icon:"🐟",description:"一枚幸运收藏",effect:"collectible"},{id:"redraw",name:"换题券",icon:"🔄",description:"免费换题一次",effect:"redraw"},{id:"immune",name:"免罚券",icon:"🛡️",description:"免除一次惩罚",effect:"immune"},{id:"extra",name:"再抽一次",icon:"🎁",description:"下次盲盒可重抽",effect:"extra"}];
const rank=["普通","稀有","史诗","传说"] as const;
export default function Undercover({initialPlayers,onClose,onTruthOrDare}:{initialPlayers:string[];onClose:()=>void;onTruthOrDare:()=>void}){
 const seed=(initialPlayers.length?initialPlayers:["小明","小红","阿杰","圆圆"]).map((name,i)=>({id:`uc-${i}`,name,role:"平民" as Role,word:"",alive:true,used:false,votes:0}));
 const[stage,setStage]=useState<Stage>("players"),[players,setPlayers]=useState<Player[]>(seed),[under,setUnder]=useState(initialPlayers.length>=9?2:1),[blank,setBlank]=useState(false),[skills,setSkills]=useState(false),[punishment,setPunishment]=useState(true),[category,setCategory]=useState("综合"),[seconds,setSeconds]=useState(20),[skip,setSkip]=useState(false),[custom,setCustom]=useState(""),[viewer,setViewer]=useState(0),[shown,setShown]=useState(false),[skillChoices,setSkillChoices]=useState<Skill[]>([]),[round,setRound]=useState(1),[turn,setTurn]=useState(0),[left,setLeft]=useState(20),[running,setRunning]=useState(false),[order,setOrder]=useState<string[]>([]),[out,setOut]=useState<Player|null>(null),[winner,setWinner]=useState(""),[event,setEvent]=useState<typeof EVENTS[number]|null>(null),[pendingEvent,setPendingEvent]=useState<typeof EVENTS[number]|null>(null),[eventLeft,setEventLeft]=useState(0),[voter,setVoter]=useState(0),[voteReady,setVoteReady]=useState(false),[voteLedger,setVoteLedger]=useState<Record<string,number>>({}),[rewards,setRewards]=useState<Reward[]>([]),[opened,setOpened]=useState<Record<string,boolean>>({}),[confirmSkill,setConfirmSkill]=useState<Player|null>(null),[targetMode,setTargetMode]=useState<"peek"|"mute"|"first"|"decoy"|null>(null),[skillOwner,setSkillOwner]=useState<Player|null>(null),[peekResult,setPeekResult]=useState(""),[mutedId,setMutedId]=useState(""),[voteTotals,setVoteTotals]=useState<Player[]>([]),[defenseNote,setDefenseNote]=useState(""),[activeVoteId,setActiveVoteId]=useState(""),[orderNotice,setOrderNotice]=useState("");
 const alive=players.filter(p=>p.alive),liveOrder=order.filter(id=>alive.some(a=>a.id===id)),current=players.find(p=>p.id===liveOrder[turn]),currentVoter=alive[voter];
 useEffect(()=>{if(!running||!seconds)return;const id=window.setInterval(()=>setLeft(x=>x<=1?(setRunning(false),0):x-1),1000);return()=>clearInterval(id)},[running,seconds]);
 const threeSkills=()=>[...SKILLS].sort(()=>Math.random()-.5).slice(0,3);
 const begin=()=>{const raw=custom.split(/[，,\n]/).map(x=>x.trim()),pool=category==="自定义"?[[raw[0]||"苹果",raw[1]||"梨"] as [string,string]]:category==="随机"?Object.values(PAIRS).flat():PAIRS[category],pair=pool[Math.floor(Math.random()*pool.length)],ids=[...players.map(p=>p.id)].sort(()=>Math.random()-.5),u=new Set(ids.slice(0,under)),b=blank?ids[under]:"",next=players.map(p=>({...p,role:p.id===b?"白板" as Role:u.has(p.id)?"卧底" as Role:"平民" as Role,word:p.id===b?"":u.has(p.id)?pair[1]:pair[0],alive:true,skill:undefined,used:false,votes:0}));setPlayers(next);setOrder(ids);setEventLeft(Math.floor(Math.random()*4));setViewer(0);setShown(false);setSkillChoices([]);setStage("reveal")};
 const advanceViewer=()=>{if(viewer===players.length-1)startRound();else{setViewer(x=>x+1);setShown(false);setSkillChoices([])}};
 const chooseSkill=(skill:Skill)=>{setPlayers(ps=>ps.map((p,i)=>i===viewer?{...p,skill}:p));setSkillChoices([])};
 const startRound=()=>{setTurn(0);setLeft(seconds);setRunning(!!seconds);setDefenseNote("");setStage("describe")},next=()=>{if(turn>=alive.length-1){setRunning(false);setVoter(0);setVoteReady(false);setVoteLedger({});setMutedId("");setOrderNotice("");setStage("vote")}else{setTurn(x=>x+1);setLeft(event?.name==="极速模式"?10:seconds)}};
 const skillEnabled=(p:Player,where:Stage)=>!!p.skill&&!p.used&&(p.skill.kind==="fate"||(where==="reveal"&&p.skill.kind==="order")||(where==="describe"&&p.skill.kind==="describe")||(where==="vote"&&(p.skill.kind==="vote"||p.skill.kind==="info"||p.skill.id==="first")));
 const requestSkill=(p:Player)=>{if(skillEnabled(p,stage))setConfirmSkill(p)};
 const confirmUse=()=>{const p=confirmSkill;if(!p?.skill)return;setConfirmSkill(null);if(["peek","mute","first"].includes(p.skill.id)){setSkillOwner(p);setTargetMode(p.skill.id as "peek"|"mute"|"first");return}if(p.skill.id==="cat")setPendingEvent(EVENTS[Math.floor(Math.random()*EVENTS.length)]);if(p.skill.id==="shuffle"){setOrder(o=>[...o].sort(()=>Math.random()-.5));setOrderNotice(`${p.name} 使用了「随机顺序」，描述顺序已重新打乱`)}if(p.skill.id==="captain")setActiveVoteId(p.id);setPlayers(ps=>ps.map(x=>x.id===p.id?{...x,used:true}:x));if(p.skill.id==="abstain")setTimeout(()=>cast(),0)};
 const chooseTarget=(target:Player)=>{if(!skillOwner)return;if(targetMode==="peek")setPeekResult(target.role==="卧底"?"❌ 卧底":target.role==="白板"?"❓ 特殊身份":"✅ 平民");if(targetMode==="mute")setMutedId(target.id);if(targetMode==="first"){setOrder(o=>[target.id,...o.filter(id=>id!==target.id)]);setOrderNotice(`${skillOwner.name} 使用了「指定首位」，${target.name} 将在下一轮第一个描述`)}if(targetMode==="decoy"){setOut(target);setPlayers(ps=>ps.map(p=>p.id===target.id?{...p,alive:false}:p));setDefenseNote(`${skillOwner.name} 的替身生效，${target.name} 代替出局`);setStage("voteResult")}setPlayers(ps=>ps.map(p=>p.id===skillOwner.id?{...p,used:true}:p));if(targetMode!=="peek")setTargetMode(null)};
 const cast=(target?:Player)=>{const weight=currentVoter.id===activeVoteId?2:1,nextLedger=target?{...voteLedger,[target.id]:(voteLedger[target.id]||0)+weight}:voteLedger;setVoteLedger(nextLedger);if(voter===alive.length-1)tally(nextLedger);else{setVoter(x=>x+1);setVoteReady(false);setActiveVoteId("")}};
 const tally=(ledger:Record<string,number>)=>{const totals=alive.map(p=>({...p,votes:ledger[p.id]||0})),max=Math.max(...totals.map(p=>p.votes)),top=totals.filter(p=>p.votes===max);setVoteTotals(totals);if(top.length!==1){setOut(null);setDefenseNote("本轮平票，无人出局；直接进入新一轮描述");setStage("voteResult");return}const chosen=top[0];if(chosen.skill?.id==="shield"&&!chosen.used){setPlayers(ps=>ps.map(p=>p.id===chosen.id?{...p,used:true}:p));setOut(null);setDefenseNote(`${chosen.name} 的护盾自动生效，本轮无人出局`);setStage("voteResult");return}if(chosen.skill?.id==="decoy"&&!chosen.used){setSkillOwner(chosen);setTargetMode("decoy");return}setOut(chosen);setPlayers(ps=>ps.map(p=>p.id===chosen.id?{...p,alive:false}:p));setDefenseNote("");setStage("voteResult")};
 const makeRewards=(side:string)=>{if(!punishment)return[];const winners=players.filter(p=>p.alive&&(side==="平民"?p.role!=="卧底":p.role==="卧底")),list:Reward[]=[];winners.forEach(p=>{let i=p.role==="白板"?3:p.role==="卧底"?2:0;if(p.skill?.id==="emperor")i=Math.min(3,i+1);list.push({id:`r-${Date.now()}-${p.id}`,owner:p.name,rarity:rank[i],opened:false});if(p.skill?.id==="lucky")list.push({id:`r-extra-${p.id}`,owner:p.name,rarity:"稀有",opened:false})});return list};
 const finish=()=>{const live=players.filter(p=>p.alive),u=live.filter(p=>p.role==="卧底").length,c=live.length-u;if(!u||u>=c){const side=!u?"平民":"卧底";setWinner(side);setRewards(makeRewards(side));setStage("result");return}setRound(x=>x+1);if(pendingEvent){setEvent(pendingEvent);setPendingEvent(null)}else if(eventLeft>0&&Math.random()<.7){setEventLeft(x=>x-1);setEvent(EVENTS[Math.floor(Math.random()*EVENTS.length)])}else setEvent(null);startRound()};
 const openBox=(reward:Reward)=>{const base=POSITIVE[Math.floor(Math.random()*POSITIVE.length)],item={...base,rarity:reward.rarity,weight:1};setRewards(rs=>rs.map(r=>r.id===reward.id?{...r,opened:true,item}:r));setOpened(o=>({...o,[reward.id]:true}));try{const store=JSON.parse(localStorage.getItem("cat_mystery_boxes")||"{}"),old=store[reward.owner]||{items:[],bravery:0,completed:0,history:[],lastUsed:{}};store[reward.owner]={...old,items:[...old.items,item].slice(-(old.capacity||3)),history:[`谁是卧底奖励：${reward.rarity}·${item.name}`,...old.history].slice(0,15)};localStorage.setItem("cat_mystery_boxes",JSON.stringify(store))}catch{}};
 const keepBox=(reward:Reward)=>{try{const saved=JSON.parse(localStorage.getItem("undercover_unopened_boxes")||"[]");localStorage.setItem("undercover_unopened_boxes",JSON.stringify([{...reward,savedAt:Date.now()},...saved]))}catch{}setOpened(o=>({...o,[reward.id]:true}))};
 const settingsValid=under+(blank?1:0)<players.length;
 return <div className="fullscreen uc-screen"><div className="play-head"><button onClick={onClose}><X/></button><span>🕵️ 谁是卧底 · {round>1?`第 ${round} 轮`:"单机主持"}</span></div><div className="uc-shell">
 {stage==="players"&&<><Header icon="🐾" title="谁今晚最会演？" text="推荐 4–12 人，6–10 人体验最佳。"/><div className="uc-player-list">{players.map((p,i)=><div className="uc-player" key={p.id}><span>{i+1}</span><input value={p.name} onChange={e=>setPlayers(ps=>ps.map(x=>x.id===p.id?{...x,name:e.target.value}:x))}/><button onClick={()=>setPlayers(ps=>ps.filter(x=>x.id!==p.id))}><X/></button></div>)}</div><div className="uc-row"><button className="secondary" onClick={()=>setPlayers(ps=>[...ps,{id:`uc-${Date.now()}`,name:`玩家 ${ps.length+1}`,role:"平民",word:"",alive:true,used:false,votes:0}])}><Plus/>添加玩家</button><button className="secondary" onClick={()=>setPlayers(ps=>[...ps].sort(()=>Math.random()-.5))}><Shuffle/>随机顺序</button></div><button className="primary uc-main" disabled={players.length<4||players.length>12} onClick={()=>setStage("settings")}>设置规则 <ChevronRight/></button></>}
 {stage==="settings"&&<><Header icon="⚙️" title="这局怎么玩？" text={`当前 ${players.length} 人，推荐 ${Math.max(1,Math.floor(players.length/5))} 名卧底。`}/><Choice title="卧底数量" values={["1","2","3"]} value={String(under)} set={v=>setUnder(+v)}/><div className="uc-toggles"><Toggle label="加入白板（没有词）" value={blank} set={setBlank}/><Toggle label="一次性技能模式（熟人局）" value={skills} set={setSkills}/><Toggle label="允许跳过描述" value={skip} set={setSkip}/><Toggle label="败者真心话大冒险 + 胜者盲盒" value={punishment} set={setPunishment}/></div>{!punishment&&<p className="uc-policy">已关闭赛后惩罚，因此本局不会发放胜利者盲盒。</p>}<Choice title="词库分类" values={[...Object.keys(PAIRS),"随机","自定义"]} value={category} set={setCategory}/>{category==="自定义"&&<textarea className="uc-custom" value={custom} onChange={e=>setCustom(e.target.value)} placeholder="输入两个相近词：苹果，梨"/>}<Choice title="描述倒计时" values={["15","20","30","无限"]} value={seconds?String(seconds):"无限"} set={v=>setSeconds(v==="无限"?0:+v)}/><div className="uc-feature"><b>🐱 命运事件</b><span>每局随机触发 0–3 次，让描述规则突然改变</span></div><button className="primary uc-main" disabled={!settingsValid} onClick={begin}><Sparkles/>随机身份，开始传阅</button></>}
 {stage==="reveal"&&(()=>{const p=players[viewer];return <><Header icon="🤫" title={`请把手机交给 ${p.name}`} text={`${viewer+1} / ${players.length} · 身份与技能都要保密`}/>{shown?<><div className={`uc-role ${p.role}`}><CatSprite state={p.role==="白板"?3:4}/><small>你的身份</small><b>{p.role}</b><h1>{p.word||"？？？"}</h1><p>{p.role==="白板"?"没有词，靠描述猜出来。":"记住词语，千万别说出口。"}</p></div>{skills&&!p.skill&&(skillChoices.length?<SkillPicker choices={skillChoices} onPick={chooseSkill}/>:<button className="secondary uc-main" onClick={()=>setSkillChoices(threeSkills())}><Sparkles/>抽取 3 个技能</button>)}{p.skill&&<SkillStatus player={p} enabled={skillEnabled(p,"reveal")} onClick={()=>requestSkill(p)}/>}</>:<button className="uc-secret" onClick={()=>setShown(true)}><CatSprite state={5}/><b>点击查看身份</b><small>ฅ 确认旁边没有偷看的猫 ฅ</small></button>}<button className="primary uc-main" disabled={!shown||(skills&&!p.skill)} onClick={advanceViewer}>{viewer===players.length-1?"开始描述":"遮住并传给下一位"}</button></>})()}
 {stage==="describe"&&current&&<><Header icon="🎙️" title={`${current.name}，到你描述`} text={`${turn+1} / ${alive.length} · 默认只能说一句，不能做动作`}/>{orderNotice&&<div className="uc-order-notice">🔄 {orderNotice}</div>}{event&&<div className="uc-event"><CatSprite state={event.name.includes("雨")?6:event.name.includes("极速")?10:event.name.includes("顺序")?11:8}/><span>ฅ^•ﻌ•^ฅ 命运事件！</span><h2>{event.name}</h2><p>{event.text}</p></div>}{mutedId===current.id&&<div className="uc-muted-alert">🔇 禁言生效：{current.name} 被禁言，本轮最多只能说三个字</div>}<div className={`uc-timer ${left<=5&&seconds?"urgent":""}`}><small>{seconds?"剩余时间":"不限时间"}</small><b>{seconds?`${left}″`:"∞"}</b>{seconds>0&&<button onClick={()=>setRunning(x=>!x)}>{running?"暂停":"继续"}</button>}</div>{current.skill&&<SkillStatus player={current} enabled={skillEnabled(current,"describe")} onClick={()=>requestSkill(current)}/>}<div className="uc-row"><button className="secondary" disabled={!skip&&current.skill?.id!=="silent"} onClick={next}>放弃描述</button><button className="primary" onClick={next}>{turn===alive.length-1?"逐人投票":"下一位"}</button></div></>}
 {stage==="vote"&&currentVoter&&<><Header icon="🗳️" title={`请把手机交给 ${currentVoter.name}`} text={`${voter+1} / ${alive.length} · 每个人的投票都保密`}/>{!voteReady?<button className="uc-secret vote" onClick={()=>setVoteReady(true)}><CatSprite state={12}/><b>开始我的投票</b><small>确认旁边的人看不到屏幕</small></button>:<>{currentVoter.skill&&<SkillStatus player={currentVoter} enabled={skillEnabled(currentVoter,"vote")} onClick={()=>requestSkill(currentVoter)}/>}<div className="uc-vote-grid">{alive.filter(p=>p.id!==currentVoter.id).map(p=><button key={p.id} onClick={()=>cast(p)}><span>{p.name.slice(0,1)}</span><b>{p.name}</b><small>投给 TA</small></button>)}</div></>}</>}
 {stage==="voteResult"&&<div className="uc-center"><CatSprite state={out?15:13}/><small>投票统计</small><h1>{out?`${out.name} 出局！`:"本轮无人出局"}</h1>{defenseNote&&<p className="uc-defense-note">{defenseNote}</p>}<div className="uc-scoreboard">{voteTotals.map(p=><div key={p.id}><b>{p.name}</b><span>{p.votes} 票</span>{out?.id===p.id&&<em>出局 · {out.role}</em>}</div>)}</div>{out&&<div className="uc-out-role"><small>出局者身份</small><b>{out.role}</b></div>}<button className="primary uc-main" onClick={finish}>判断胜负并继续 <ChevronRight/></button></div>}
 {stage==="result"&&<div className="uc-center uc-result"><CatSprite state={winner==="平民"?2:1}/><small>游戏结束 · ฅ( ̳• ·̫ • ̳ฅ)</small><h1>🏆 {winner}胜利！</h1>{punishment?<><div className="uc-reward-list"><h2>🎁 胜利者奖励盲盒</h2><p>奖励池只有正向效果。可以现在开启并装入背包，也可以留到以后。</p>{rewards.map(r=><div className="uc-reward" key={r.id}><span>🎁</span><div><b>{r.owner} · {r.rarity}盲盒</b><small>{r.opened?`${r.item?.icon} ${r.item?.name} 已装入背包`:opened[r.id]?"已保存为未开启盲盒":"等待选择"}</small></div>{!opened[r.id]&&!r.opened&&<><button onClick={()=>openBox(r)}>开启</button><button onClick={()=>keepBox(r)}>不开</button></>}</div>)}</div><div className="uc-punishment"><b>🔥 败者惩罚</b><p>整局已经结束，可以直接进入真心话大冒险；任何人仍可选择跳过。</p><button className="primary" onClick={onTruthOrDare}>进入真心话大冒险</button><button className="secondary" onClick={onClose}>跳过惩罚</button></div></>:<div className="uc-policy">赛后惩罚已关闭，本局不发放奖励盲盒。</div>}<button className="text-btn" onClick={()=>{setStage("players");setRound(1);setWinner("")}}><RotateCcw/>再来一局</button></div>}
 {confirmSkill&&<div className="uc-modal"><div><CatSprite state={9}/><h2>确认使用「{confirmSkill.skill?.name}」？</h2><p>{confirmSkill.skill?.description}<br/>每局只能使用一次，使用后无法撤回。</p><section><button className="secondary" onClick={()=>setConfirmSkill(null)}>再想想</button><button className="primary" onClick={confirmUse}>确认使用</button></section></div></div>}
 {targetMode&&<div className="uc-modal"><div><CatSprite state={targetMode==="peek"?0:targetMode==="decoy"?15:8}/><h2>{targetMode==="peek"?"想偷看谁？":targetMode==="mute"?"下一轮禁言谁？":targetMode==="first"?"指定谁第一个描述？":`${skillOwner?.name} 被淘汰，请选择一名替身`}</h2><p>{targetMode==="peek"?"只显示阵营，不会显示具体词语。":targetMode==="decoy"?`${skillOwner?.name} 将留在场上，被选中的玩家代替出局。`:"请选择一位仍在场的其他玩家。"}</p><div className="uc-targets">{alive.filter(p=>p.id!==skillOwner?.id).map(p=><button key={p.id} onClick={()=>chooseTarget(p)}>{p.name}</button>)}</div><button className="text-btn" onClick={()=>{setTargetMode(null);setSkillOwner(null);setPeekResult("")}}>取消</button></div></div>}
 {peekResult&&<div className="uc-modal top"><div><CatSprite state={0}/><h2>查看结果</h2><strong className="uc-peek-result">{peekResult}</strong><p>把结果记在心里，不要让其他人看见喵。</p><button className="primary uc-main" onClick={()=>{setPeekResult("");setTargetMode(null);setSkillOwner(null)}}>知道了，藏好</button></div></div>}
 </div></div>
}
function Header({icon,title,text}:{icon:string;title:string;text:string}){const state=icon==="🐾"?0:icon==="⚙️"?1:icon==="🤫"?4:icon==="🎙️"?8:12;return <header className="uc-header"><CatSprite state={state} className="header-cat"/><div><h1>{title}</h1><p>{text}</p></div></header>}
function Choice({title,values,value,set}:{title:string;values:string[];value:string;set:(v:string)=>void}){return <section className="uc-choice"><b>{title}</b><div>{values.map(v=><button key={v} className={value===v?"on":""} onClick={()=>set(v)}>{v}{/^\d+$/.test(v)&&title.includes("倒计时")?"秒":""}</button>)}</div></section>}
function Toggle({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <label><span>{label}</span><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/><i/></label>}
function SkillPicker({choices,onPick}:{choices:Skill[];onPick:(s:Skill)=>void}){return <section className="uc-skill-picker"><h2>请选择一个技能</h2><p>三选一，每局最多使用一次。</p>{choices.map(s=><button key={s.id} onClick={()=>onPick(s)}><span>{s.icon}</span><div><b>{s.name}</b><small>{s.timing}</small><p>{s.description}</p></div><em>选择</em></button>)}</section>}
function SkillStatus({player,enabled,onClick}:{player:Player;enabled:boolean;onClick:()=>void}){const s=player.skill!;return <button className={`uc-skill ${enabled?"available":"disabled"}`} disabled={!enabled} onClick={onClick}><span>{s.icon} {s.name}{player.used?" · 已使用":""}</span><small>{s.timing} · {s.description}</small><em>{enabled?"本阶段可使用":"当前阶段不可使用"}</em></button>}
function CatSprite({state,className=""}:{state:number;className?:string}){const x=state%4,y=Math.floor(state/4);return <span className={`uc-cat-sprite ${className}`} style={{backgroundPosition:`${x*33.333}% ${y*33.333}%`}} role="img" aria-label="谁是卧底小猫表情"/>}
