"use client";
import {useEffect,useState} from "react";
import {ChevronRight,Plus,RotateCcw,Shuffle,Sparkles,Trophy,X} from "lucide-react";
type Stage="players"|"settings"|"reveal"|"describe"|"vote"|"out"|"result";
type Role="平民"|"卧底"|"白板";
type Player={id:string;name:string;role:Role;word:string;alive:boolean;skill:string;used:boolean;votes:number};
const PAIRS:Record<string,[string,string][]>= {综合:[["牛奶","豆浆"],["橙子","橘子"],["雨伞","雨衣"]],电影:[["哈利·波特","指环王"],["泰坦尼克号","罗马假日"]],校园:[["班主任","辅导员"],["校服","运动服"]],网络热梗:[["显眼包","社牛"],["吃瓜","围观"]],情侣:[["牵手","拥抱"],["约会","旅行"]],美食:[["饺子","馄饨"],["火锅","麻辣烫"]],动物:[["猫","老虎"],["海豚","鲨鱼"]]};
const SKILLS=["🔍 偷看","🛡 护盾","🔄 换位","❓ 多问","🎭 沉默","🎲 重投","👑 队长","🎁 好运"];
const EVENTS=[{icon:"🌧",name:"猫咪下雨",text:"每个人只能说三个字"},{icon:"🌙",name:"月黑风高",text:"不能描述颜色"},{icon:"🤫",name:"安静模式",text:"每人只能说一句"},{icon:"🪞",name:"镜像世界",text:"描述顺序反过来"},{icon:"🎭",name:"演技模式",text:"必须带表情描述"},{icon:"🎲",name:"极速模式",text:"每个人只有 10 秒"},{icon:"🎤",name:"Rap 模式",text:"描述必须押韵"}];
export default function Undercover({initialPlayers,onClose}:{initialPlayers:string[];onClose:()=>void}){
 const seed=(initialPlayers.length?initialPlayers:["小明","小红","阿杰","圆圆"]).map((name,i)=>({id:`uc-${i}`,name,role:"平民" as Role,word:"",alive:true,skill:"",used:false,votes:0}));
 const[stage,setStage]=useState<Stage>("players"),[players,setPlayers]=useState<Player[]>(seed),[under,setUnder]=useState(initialPlayers.length>=9?2:1),[blank,setBlank]=useState(false),[skills,setSkills]=useState(true),[category,setCategory]=useState("综合"),[seconds,setSeconds]=useState(20),[skip,setSkip]=useState(false),[custom,setCustom]=useState(""),[viewer,setViewer]=useState(0),[shown,setShown]=useState(false),[round,setRound]=useState(1),[turn,setTurn]=useState(0),[left,setLeft]=useState(20),[running,setRunning]=useState(false),[order,setOrder]=useState<string[]>([]),[out,setOut]=useState<Player|null>(null),[winner,setWinner]=useState(""),[event,setEvent]=useState<typeof EVENTS[number]|null>(null),[eventLeft,setEventLeft]=useState(0);
 const alive=players.filter(p=>p.alive),liveOrder=order.filter(id=>alive.some(a=>a.id===id)),current=players.find(p=>p.id===liveOrder[turn]);
 useEffect(()=>{if(!running||!seconds)return;const id=window.setInterval(()=>setLeft(x=>x<=1?(setRunning(false),0):x-1),1000);return()=>clearInterval(id)},[running,seconds]);
 const begin=()=>{const raw=custom.split(/[，,\n]/).map(x=>x.trim()),pool=category==="自定义"?[[raw[0]||"苹果",raw[1]||"梨"] as [string,string]]:category==="随机"?Object.values(PAIRS).flat():PAIRS[category],pair=pool[Math.floor(Math.random()*pool.length)],ids=[...players.map(p=>p.id)].sort(()=>Math.random()-.5),u=new Set(ids.slice(0,under)),b=blank?ids[under]:"",next=players.map((p,i)=>({...p,role:p.id===b?"白板" as Role:u.has(p.id)?"卧底" as Role:"平民" as Role,word:p.id===b?"":u.has(p.id)?pair[1]:pair[0],alive:true,skill:skills?SKILLS[i%SKILLS.length]:"",used:false,votes:0}));setPlayers(next);setOrder(ids);setEventLeft(Math.floor(Math.random()*4));setStage("reveal")};
 const startRound=()=>{setTurn(0);setLeft(seconds);setRunning(!!seconds);setStage("describe")},next=()=>{if(turn>=alive.length-1){setRunning(false);setStage("vote")}else{setTurn(x=>x+1);setLeft(event?.name==="极速模式"?10:seconds)}};
 const tally=()=>{const max=Math.max(...alive.map(p=>p.votes)),top=alive.filter(p=>p.votes===max);setPlayers(ps=>ps.map(p=>({...p,votes:0})));if(top.length!==1){setRound(x=>x+1);startRound();return}setOut(top[0]);setPlayers(ps=>ps.map(p=>p.id===top[0].id?{...p,alive:false}:p));setStage("out")};
 const finish=()=>{const live=players.filter(p=>p.alive&&p.id!==out?.id),u=live.filter(p=>p.role==="卧底").length,c=live.length-u;if(!u||u>=c){const side=!u?"平民":"卧底";setWinner(side);setStage("result");const rewards=JSON.parse(localStorage.getItem("undercover_rewards")||"[]");localStorage.setItem("undercover_rewards",JSON.stringify([{date:Date.now(),winner:side,players:players.filter(p=>(side==="平民"?p.role!=="卧底":p.role==="卧底")).map(p=>p.name)},...rewards].slice(0,20)));return}setRound(x=>x+1);if(eventLeft>0&&Math.random()<.7){setEventLeft(x=>x-1);setEvent(EVENTS[Math.floor(Math.random()*EVENTS.length)])}else setEvent(null);startRound()};
 return <div className="fullscreen uc-screen"><div className="play-head"><button onClick={onClose}><X/></button><span>🕵️ 谁是卧底 · {round>1?`第 ${round} 轮`:"单机主持"}</span></div><div className="uc-shell">
 {stage==="players"&&<><Header icon="🐾" title="谁今晚最会演？" text="推荐 4–12 人，6–10 人体验最佳。"/><div className="uc-player-list">{players.map((p,i)=><div className="uc-player" key={p.id}><span>{i+1}</span><input value={p.name} onChange={e=>setPlayers(ps=>ps.map(x=>x.id===p.id?{...x,name:e.target.value}:x))}/><button onClick={()=>setPlayers(ps=>ps.filter(x=>x.id!==p.id))}><X/></button></div>)}</div><div className="uc-row"><button className="secondary" onClick={()=>setPlayers(ps=>[...ps,{id:`uc-${Date.now()}`,name:`玩家 ${ps.length+1}`,role:"平民",word:"",alive:true,skill:"",used:false,votes:0}])}><Plus/>添加玩家</button><button className="secondary" onClick={()=>setPlayers(ps=>[...ps].sort(()=>Math.random()-.5))}><Shuffle/>随机顺序</button></div><button className="primary uc-main" disabled={players.length<4||players.length>12} onClick={()=>setStage("settings")}>设置规则 <ChevronRight/></button></>}
 {stage==="settings"&&<><Header icon="⚙️" title="这局怎么玩？" text={`当前 ${players.length} 人，推荐 ${Math.max(1,Math.floor(players.length/5))} 名卧底。`}/><Choice title="卧底数量" values={["1","2","3"]} value={String(under)} set={v=>setUnder(+v)}/><div className="uc-toggles"><Toggle label="加入白板（没有词）" value={blank} set={setBlank}/><Toggle label="一次性技能模式" value={skills} set={setSkills}/><Toggle label="允许跳过描述" value={skip} set={setSkip}/></div><Choice title="词库分类" values={[...Object.keys(PAIRS),"随机","自定义"]} value={category} set={setCategory}/>{category==="自定义"&&<textarea className="uc-custom" value={custom} onChange={e=>setCustom(e.target.value)} placeholder="输入两个相近词：苹果，梨"/>}<Choice title="描述倒计时" values={["15","20","30","无限"]} value={seconds?String(seconds):"无限"} set={v=>setSeconds(v==="无限"?0:+v)}/><div className="uc-feature"><b>🐱 命运事件</b><span>每局随机触发 0–3 次，让描述规则突然改变</span></div><button className="primary uc-main" disabled={under+(blank?1:0)>=players.length} onClick={begin}><Sparkles/>随机身份，开始传阅</button></>}
 {stage==="reveal"&&(()=>{const p=players[viewer];return <><Header icon="🤫" title={`请把手机交给 ${p.name}`} text={`${viewer+1} / ${players.length} · 看完自动遮住`}/>{shown?<div className={`uc-role ${p.role}`}><small>你的身份</small><b>{p.role}</b><h1>{p.word||"？？？"}</h1><p>{p.role==="白板"?"没有词，靠描述猜出来。":"记住词语，千万别说出口。"}</p>{p.skill&&<div>一次性技能 · <strong>{p.skill}</strong></div>}</div>:<button className="uc-secret" onClick={()=>setShown(true)}><span>🐱</span><b>点击查看身份</b></button>}<button className="primary uc-main" disabled={!shown} onClick={()=>{if(viewer===players.length-1)startRound();else{setViewer(x=>x+1);setShown(false)}}}>{viewer===players.length-1?"开始描述":"遮住并传给下一位"}</button></>})()}
 {stage==="describe"&&current&&<><Header icon="🎙️" title={`${current.name}，到你描述`} text={`${turn+1} / ${alive.length} · 只能描述，不能说词`}/>{event&&<div className="uc-event"><span>🐱 命运事件！</span><i>{event.icon}</i><h2>{event.name}</h2><p>{event.text}</p></div>}<div className={`uc-timer ${left<=5&&seconds?"urgent":""}`}><small>{seconds?"剩余时间":"不限时间"}</small><b>{seconds?`${left}″`:"∞"}</b>{seconds>0&&<button onClick={()=>setRunning(x=>!x)}>{running?"暂停":"继续"}</button>}</div>{current.skill&&!current.used&&<button className="uc-skill" onClick={()=>setPlayers(ps=>ps.map(p=>p.id===current.id?{...p,used:true}:p))}><span>{current.skill}</span><small>点击标记已使用</small></button>}<div className="uc-row"><button className="secondary" disabled={!skip} onClick={next}>跳过</button><button className="primary" onClick={next}>{turn===alive.length-1?"去投票":"下一位"}</button></div></>}
 {stage==="vote"&&<><Header icon="🗳️" title="谁最像卧底？" text="房主按大家的选择逐票记录。"/><div className="uc-vote-grid">{alive.map(p=><button key={p.id} onClick={()=>setPlayers(ps=>ps.map(x=>x.id===p.id?{...x,votes:x.votes+(x.skill.includes("队长")&&!x.used?2:1)}:x))}><span>{p.name.slice(0,1)}</span><b>{p.name}</b><small>{"⭐".repeat(p.votes)||"暂无票"}</small></button>)}</div><button className="primary uc-main" disabled={!players.some(p=>p.votes)} onClick={tally}><Trophy/>统计最高票</button><p className="uc-hint">平票将进入新一轮描述，不重新投票</p></>}
 {stage==="out"&&out&&<div className="uc-center"><span className="uc-bigcat">{out.role==="卧底"?"😼":"🙀"}</span><small>本轮淘汰</small><h1>{out.name} 出局！</h1><div className="uc-out-role"><small>真实身份</small><b>{out.role}</b></div><button className="primary uc-main" onClick={finish}>判断胜负并继续 <ChevronRight/></button></div>}
 {stage==="result"&&<div className="uc-center uc-result"><span className="uc-bigcat">🎊</span><small>游戏结束</small><h1>🏆 {winner}胜利！</h1><p>{winner==="平民"?"所有卧底都已出局。":"卧底人数已不少于平民。"}</p><div className="uc-feature"><b>🎁 小猫盲盒已发放</b><span>{winner==="卧底"?"获胜卧底获得史诗盲盒":"存活平民获得普通盲盒，白板获得传说盲盒"}</span></div><button className="primary uc-main" onClick={()=>{setStage("players");setRound(1);setWinner("")}}><RotateCcw/>再来一局</button><button className="text-btn" onClick={onClose}>返回猫咪派对</button></div>}
 </div></div>
}
function Header({icon,title,text}:{icon:string;title:string;text:string}){return <header className="uc-header"><span>{icon}</span><div><h1>{title}</h1><p>{text}</p></div></header>}
function Choice({title,values,value,set}:{title:string;values:string[];value:string;set:(v:string)=>void}){return <section className="uc-choice"><b>{title}</b><div>{values.map(v=><button key={v} className={value===v?"on":""} onClick={()=>set(v)}>{v}{/^\d+$/.test(v)&&title.includes("倒计时")?"秒":""}</button>)}</div></section>}
function Toggle({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <label><span>{label}</span><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/><i/></label>}
